export const groups = [
  // {
  //   name: "Regular Verbs",
  //   iconName: "walk",
  //   exercises: [
  //     { englishWord: "divide", spanishTranslation: "dividir", rating: 0, image: "https://i.giphy.com/media/6PDD11h741IpG/200w.gif"},
  //     { englishWord: "support", spanishTranslation: "soportar", rating: 0, image: "https://i.giphy.com/media/ew8hN0QnkoaOdTn2Eo/200w.gif"},
  //     { englishWord: "follow", spanishTranslation: "seguir", rating: 0, image: "https://i.giphy.com/media/TisFptjsMKzYp1fAzo/200w.gif"},
  //     { englishWord: "complete", spanishTranslation: "completar", rating: 0, image: "https://i.giphy.com/media/Q5RiiXiUWWVjvE3rER/200w.gif"},
  //     { englishWord: "suck", spanishTranslation: "chupar", rating: 0, image: "https://i.giphy.com/media/FnxHqXpcyYN32/200w.gif"},
  //     { englishWord: "pull", spanishTranslation: "halar - tirar de", rating: 0, image: "https://i.giphy.com/media/SsIZAm4IDC6yUQMa45/200w.gif"},
  //     { englishWord: "practice", spanishTranslation: "practicar", rating: 0, image: "https://i.giphy.com/media/xT9DPjkNXsQuoZva6c/200w.gif"},
  //     { englishWord: "lower", spanishTranslation: "bajar - reducir - disminuir", rating: 0, image: "https://i.giphy.com/media/g8tLOZ6RWlDvRf5Kfp/200w.gif"},
  //     { englishWord: "kiss", spanishTranslation: "besar", rating: 0, image: "https://i.giphy.com/media/l2Je2M4Nfrit0L7sQ/200w.gif"},
  //     { englishWord: "wed", spanishTranslation: "casar(se) - unirse con", rating: 0, image: "https://i.giphy.com/media/urgh3QkW9wgG8goYCQ/200w.gif"},
  //     { englishWord: "smile", spanishTranslation: "sonreir", rating: 0, image: "https://i.giphy.com/media/QTrG6mjkHEkpFR3DqX/200w.gif"},
  //     { englishWord: "fish", spanishTranslation: "pescar", rating: 0, image: "https://i.giphy.com/media/Xy0VPXTENJyG2HFqtr/200w.gif"},
  //     { englishWord: "rest", spanishTranslation: "descansar - reposar", rating: 0, image: "https://i.giphy.com/media/fdlcvptCs4qsM/200w.gif"},
  //     { englishWord: "warm", spanishTranslation: "calentar(se) - recalentar", rating: 0, image: "https://i.giphy.com/media/3o6Zt2FsmthIOdUm5y/200w.gif"},
  //     { englishWord: "visit", spanishTranslation: "visitar - hacer visitas", rating: 0, image: "https://i.giphy.com/media/3o6ZtaDUO4wr2LJCqk/200w.gif"},
  //     { englishWord: "descend", spanishTranslation: "descender - bajar", rating: 0, image: "https://i.giphy.com/media/11nPtzt27joQQ8/200w.gif"},
  //     { englishWord: "add", spanishTranslation: "añadir - sumar", rating: 0, image: "https://i.giphy.com/media/3o6MbmXIt1qUsNzfu8/200w.gif"},
  //     { englishWord: "taste", spanishTranslation: "saborear - catar - probar", rating: 0, image: "https://i.giphy.com/media/l2Sq0ogljPAubE2nS/200w.gif"},
  //     { englishWord: "ski", spanishTranslation: "esquiar", rating: 0, image: "https://i.giphy.com/media/l0HlUVUnpHH36zoek/200w.gif"},
  //     { englishWord: "flee", spanishTranslation: "evitar - huir de", rating: 0, image: "https://i.giphy.com/media/S3PjeN6iPYyxJYvdji/200w.gif"},
  //     { englishWord: "look", spanishTranslation: "mirar - fijar mirada en algo", rating: 0, image: "https://i.giphy.com/media/kd9BlRovbPOykLBMqX/200w.gif"},
  //     { englishWord: "shout", spanishTranslation: "gritar", rating: 0, image: "https://i.giphy.com/media/IVT4vN0Ywp93aeKSzd/200w.gif"},
  //     { englishWord: "decide", spanishTranslation: "decidir", rating: 0, image: "https://i.giphy.com/media/xUA7aUNw61j9Vdzs0U/200w.gif"},
  //     { englishWord: "disagree", spanishTranslation: "discrepar - no estar de acuerdo", rating: 0, image: "https://i.giphy.com/media/l0HlFq5c61LraxYaI/200w.gif"},
  //     { englishWord: "pack", spanishTranslation: "empacar - envasar", rating: 0, image: "https://i.giphy.com/media/M8vBiv9mgpHDGpqL9y/200w.gif"},
  //     { englishWord: "seem", spanishTranslation: "parecer", rating: 0, image: "https://i.giphy.com/media/rVeJCzA8bCQUk4JQ4v/200w.gif"},
  //     { englishWord: "offer", spanishTranslation: "ofrecer", rating: 0, image: "https://i.giphy.com/media/l2QEdZMha3XrvypMY/200w.gif"},
  //     { englishWord: "circle", spanishTranslation: "rodear - hacer un circulo", rating: 0, image: "https://i.giphy.com/media/OtP2Jj6IuVbhu/200w.gif"},
  //     { englishWord: "climb", spanishTranslation: "subir - trepar - escalar", rating: 0, image: "https://i.giphy.com/media/kfLIA5rPSEdYrGvWLw/200w.gif"},
  //     { englishWord: "play", spanishTranslation: "jugar - tocar - reproducir", rating: 0, image: "https://i.giphy.com/media/YgsGYbakNrZg3sVmop/200w.gif"},
  //     { englishWord: "vanish", spanishTranslation: "desvanecer(se) - desaparecer", rating: 0, image: "https://i.giphy.com/media/kelU5SPX69mnvlKts2/200w.gif"},
  //     { englishWord: "destroy", spanishTranslation: "destruir", rating: 0, image: "https://i.giphy.com/media/10UHehEC098kAE/200w.gif"},
  //     { englishWord: "squeeze", spanishTranslation: "apretar", rating: 0, image: "https://i.giphy.com/media/TLIed7IwyosvDnXZLD/200w.gif"},
  //     { englishWord: "grate", spanishTranslation: "rallar - raspar", rating: 0, image: "https://i.giphy.com/media/co4PLMN4BYHdC4ZPuW/200w.gif"},
  //     { englishWord: "cool", spanishTranslation: "enfriar - refrescar(se) -  calmar(se)", rating: 0, image: "https://i.giphy.com/media/mGK0QLlJtLkzIx43PI/200w.gif"},
  //     { englishWord: "spoil", spanishTranslation: "estropear - echar a perder - mimar", rating: 0, image: "https://i.giphy.com/media/9mEPFPEwBA0JlDvYlQ/200w.gif"},
  //     { englishWord: "carry", spanishTranslation: "llevar", rating: 0, image: "https://i.giphy.com/media/dXA0rJGesbvFHn3RkP/200w.gif"},
  //     { englishWord: "dream", spanishTranslation: "soñar", rating: 0, image: "https://i.giphy.com/media/3o8doTrOWoQMV8h74k/200w.gif"},
  //     { englishWord: "work", spanishTranslation: "trabajar - funcionar", rating: 0, image: "https://i.giphy.com/media/13rQ7rrTrvZXlm/200w.gif"},
  //     { englishWord: "punish", spanishTranslation: "castigar", rating: 0, image: "https://i.giphy.com/media/pRotk2UQTsozm/200w.gif"},
  //     { englishWord: "paint", spanishTranslation: "pintar", rating: 0, image: "https://i.giphy.com/media/hQu3aAkP2I0bn3k1hl/200w.gif"},
  //     { englishWord: "talk", spanishTranslation: "hablar - conversar", rating: 0, image: "https://i.giphy.com/media/M8xmO5ZcLPtAY/200w.gif"},
  //     { englishWord: "peel", spanishTranslation: "pelar", rating: 0, image: "https://i.giphy.com/media/p3P5xLjTI2iu13ronY/200w.gif"},
  //     { englishWord: "underline", spanishTranslation: "subrayar", rating: 0, image: "https://i.giphy.com/media/KBDGEAI1JHIftkUhjD/200w.gif"},
  //     { englishWord: "discover", spanishTranslation: "descubrir", rating: 0, image: "https://i.giphy.com/media/0IGsC1JY4k0LzdDJfb/200w.gif"},
  //     { englishWord: "check", spanishTranslation: "comprobar -  chequear -  verificar", rating: 0, image: "https://i.giphy.com/media/kLOkqcrdC5mrCE7k7G/200w.gif"},
  //     { englishWord: "stay", spanishTranslation: "permanecer - quedarse - durar", rating: 0, image: "https://i.giphy.com/media/TGUIq0O5s4XJSnefJ3/200w.gif"},
  //     { englishWord: "cheer", spanishTranslation: "victorear -  alegrar -  animar -  aplaudir", rating: 0, image: "https://i.giphy.com/media/11sBLVxNs7v6WA/200w.gif"},
  //     { englishWord: "speed", spanishTranslation: "acelerar - apresurarse - darse prisa", rating: 0, image: "https://i.giphy.com/media/qxM03tz9rg4RYThmkG/200w.gif"},
  //     { englishWord: "count", spanishTranslation: "contar", rating: 0, image: "https://i.giphy.com/media/xUPGcqaVH1cDeKZTBS/200w.gif"},
  //     { englishWord: "laugh", spanishTranslation: "reir(se)", rating: 0, image: "https://i.giphy.com/media/CoDp6NnSmItoY/200w.gif"},
  //     { englishWord: "mop", spanishTranslation: "trapear - fregar", rating: 0, image: "https://i.giphy.com/media/l2YWkhCvZ2ufDVar6/200w.gif"},
  //     { englishWord: "cancel", spanishTranslation: "cancelar", rating: 0, image: "https://i.giphy.com/media/l4FGlqf3GnH6mXY08/200w.gif"},
  //     { englishWord: "pronounce", spanishTranslation: "pronunciar", rating: 0, image: "https://i.giphy.com/media/l2JdZtmjxPJ2M1d9C/200w.gif"},
  //     { englishWord: "describe", spanishTranslation: "describir", rating: 0, image: "https://i.giphy.com/media/STLj8QUhg25pe/200w.gif"},
  //     { englishWord: "listen", spanishTranslation: "escuchar", rating: 0, image: "https://i.giphy.com/media/4oMoIbIQrvCjm/200w.gif"},
  //     { englishWord: "fill", spanishTranslation: "llenar - rellenar", rating: 0, image: "https://i.giphy.com/media/xT9IgFQsNYi1zBUiyc/200w.gif"},
  //     { englishWord: "discuss", spanishTranslation: "discutir", rating: 0, image: "https://i.giphy.com/media/kSacoMuLSoNTfInwsB/200w.gif"},
  //     { englishWord: "splash", spanishTranslation: "salpicar - rociar", rating: 0, image: "https://i.giphy.com/media/iNZffK78WQ0LF3ZWLb/200w.gif"},
  //     { englishWord: "inspect", spanishTranslation: "inspeccionar", rating: 0, image: "https://i.giphy.com/media/jFhWlcjuUkEacx4ZCU/200w.gif"},
  //     { englishWord: "help", spanishTranslation: "ayudar - socorrer", rating: 0, image: "https://i.giphy.com/media/l0Extn1wgzXyZn0J2/200w.gif"},
  //     { englishWord: "order", spanishTranslation: "ordenar - disponer", rating: 0, image: "https://i.giphy.com/media/03xd6iUVUOSgSMupzO/200w.gif"},
  //     { englishWord: "assign", spanishTranslation: "asignar", rating: 0, image: "https://i.giphy.com/media/l2SpQlNVrKuypajWE/200w.gif"},
  //     { englishWord: "plan", spanishTranslation: "planear", rating: 0, image: "https://i.giphy.com/media/yv1ggi3Cbase05a8iS/200w.gif"},
  //     { englishWord: "move", spanishTranslation: "mover - trastear", rating: 0, image: "https://i.giphy.com/media/3F1pInHV8vz5HXfAzM/200w.gif"},
  //     { englishWord: "remember", spanishTranslation: "recordar -  acordarse", rating: 0, image: "https://i.giphy.com/media/3orieTQUh6WCMckclq/200w.gif"},
  //     { englishWord: "wait", spanishTranslation: "esperar", rating: 0, image: "https://i.giphy.com/media/l0HlBO7eyXzSZkJri/200w.gif"},
  //     { englishWord: "enjoy", spanishTranslation: "gozar(de) - disfrutar disfrutar", rating: 0, image: "https://i.giphy.com/media/ifM0rVliHWXfsEEQOS/200w.gif"},
  //     { englishWord: "believe", spanishTranslation: "creer", rating: 0, image: "https://i.giphy.com/media/3o6wrGqTd5HbwPJkYw/200w.gif"},
  //     { englishWord: "share", spanishTranslation: "compartir", rating: 0, image: "https://i.giphy.com/media/1oFqxMYv5JQvuFtX8o/200w.gif"},
  //     { englishWord: "watch", spanishTranslation: "observar - velar - vigilar", rating: 0, image: "https://i.giphy.com/media/n6Gk6pAMeP9NS/200w.gif"},
  //     { englishWord: "lead", spanishTranslation: "conducir - liderar", rating: 0, image: "https://i.giphy.com/media/3orif4BtRvTgRedJF6/200w.gif"},
  //     { englishWord: "wash", spanishTranslation: "lavar - fregar - mojar", rating: 0, image: "https://i.giphy.com/media/oM8CvBlVubezC/200w.gif"},
  //     { englishWord: "calm", spanishTranslation: "calmar", rating: 0, image: "https://i.giphy.com/media/2ilegKh8fMdJAVqbG2/200w.gif"},
  //     { englishWord: "copy", spanishTranslation: "copiar", rating: 0, image: "https://i.giphy.com/media/FZPBHxQbXbOUUB69Q7/200w.gif"},
  //     { englishWord: "attach", spanishTranslation: "unir - juntar - sujetar - pegar", rating: 0, image: "https://i.giphy.com/media/Y1dzeiMAHY3ohSFPZC/200w.gif"},
  //     { englishWord: "worry", spanishTranslation: "preocupar", rating: 0, image: "https://i.giphy.com/media/14oABfwMhnvZfi/200w.gif"},
  //     { englishWord: "award", spanishTranslation: "otorgar", rating: 0, image: "https://i.giphy.com/media/CMVMPGhA7yHdYxo7Xf/200w.gif"},
  //     { englishWord: "like", spanishTranslation: "gustar - querer", rating: 0, image: "https://i.giphy.com/media/l0IyccEqUTO7xy9Ec/200w.gif"},
  //     { englishWord: "dance", spanishTranslation: "bailar", rating: 0, image: "https://i.giphy.com/media/EFgksQHxImgta/200w.gif"},
  //     { englishWord: "excuse", spanishTranslation: "excusar", rating: 0, image: "https://i.giphy.com/media/SY44A3CMBwM83yI7t2/200w.gif"},
  //     { englishWord: "place", spanishTranslation: "poner - colocar - situar", rating: 0, image: "https://i.giphy.com/media/hSjSZkQtCHdAbgEZPc/200w.gif"},
  //     { englishWord: "sprinkle", spanishTranslation: "rociar", rating: 0, image: "https://i.giphy.com/media/l4Jz3a8jO92crUlWM/200w.gif"},
  //     { englishWord: "celebrate", spanishTranslation: "celebrar", rating: 0, image: "https://i.giphy.com/media/jcwDyr6UBjLebH863a/200w.gif"},
  //     { englishWord: "assist", spanishTranslation: "asistir - ayudar ", rating: 0, image: "https://i.giphy.com/media/kD4pknHevDUQNOTSbl/200w.gif"},
  //     { englishWord: "mix", spanishTranslation: "mezclar - barajar", rating: 0, image: "https://i.giphy.com/media/1X7qz2KCFnU0Il8RSk/200w.gif"},
  //     { englishWord: "defend", spanishTranslation: "defender", rating: 0, image: "https://i.giphy.com/media/nG9tIH9H7CAk9sEDfu/200w.gif"},
  //     { englishWord: "sharpen", spanishTranslation: "afilar - ampliar", rating: 0, image: "https://i.giphy.com/media/7SoghL1WjxTK9CkkpS/200w.gif"},
  //     { englishWord: "blush", spanishTranslation: "sonrojar", rating: 0, image: "https://i.giphy.com/media/rpf0Du8NasK6Q/200w.gif"},
  //     { englishWord: "attend", spanishTranslation: "atender", rating: 0, image: "https://i.giphy.com/media/6MpYHxuYBaRcD9eF4L/200w.gif"},
  //     { englishWord: "type", spanishTranslation: "mecanografiar - digitar", rating: 0, image: "https://i.giphy.com/media/3o7aCTfyhYawdOXcFW/200w.gif"},
  //     { englishWord: "clap", spanishTranslation: "aplaudir", rating: 0, image: "https://i.giphy.com/media/1236TCtX5dsGEo/200w.gif"},
  //     { englishWord: "fade", spanishTranslation: "desteñir - desvanecer(se)", rating: 0, image: "https://i.giphy.com/media/d8P7zL3QrEotHWPRrR/200w.gif"},
  //     { englishWord: "learn", spanishTranslation: "aprender", rating: 0, image: "https://i.giphy.com/media/qKltgF7Aw515K/200w.gif"},
  //     { englishWord: "chill", spanishTranslation: "resfriar", rating: 0, image: "https://i.giphy.com/media/5hxsG54XihuvDNsrCB/200w.gif"},
  //     { englishWord: "open", spanishTranslation: "abrir", rating: 0, image: "https://i.giphy.com/media/jyPWfqzhit2HEBDymN/200w.gif"},
  //     { englishWord: "prefer", spanishTranslation: "preferir", rating: 0, image: "https://i.giphy.com/media/HrFiaDpS7mP1XzJiZZ/200w.gif"},
  //     { englishWord: "use", spanishTranslation: "usar", rating: 0, image: "https://i.giphy.com/media/mgJHCuKiCy5KU/200w.gif"},
  //     { englishWord: "notice", spanishTranslation: "notar - advertir", rating: 0, image: "https://i.giphy.com/media/VPevIZhmlNOms/200w.gif"},
  //     { englishWord: "jog", spanishTranslation: "trotar", rating: 0, image: "https://i.giphy.com/media/CXLdpFUp9zsoaw3X8c/200w.gif"},
  //     { englishWord: "grade", spanishTranslation: "graduar - calificar - clasificar", rating: 0, image: "https://i.giphy.com/media/iH1rdIKYvNhOu5Z8RY/200w.gif"},
  //     { englishWord: "demostrate", spanishTranslation: "demostrar", rating: 0, image: "https://i.giphy.com/media/l1Kdb3gWBSzFgVIek/200w.gif"},
  //     { englishWord: "enroll", spanishTranslation: "inscribirse - matricular", rating: 0, image: "https://i.giphy.com/media/oyGpShr0FL7Fmdu1CG/200w.gif"},
  //     { englishWord: "stop", spanishTranslation: "parar - detener", rating: 0, image: "https://i.giphy.com/media/l4FGDLkDkCnsKwdnq/200w.gif"},
  //     { englishWord: "ask", spanishTranslation: "preguntar", rating: 0, image: "https://i.giphy.com/media/3o6ozoD1ByqYv7ARIk/200w.gif"},
  //     { englishWord: "turn", spanishTranslation: "girar - dar vueltas -  dar la vuelta", rating: 0, image: "https://i.giphy.com/media/ohMtDzrhrWgnK/200w.gif"},
  //     { englishWord: "weigh", spanishTranslation: "pesar", rating: 0, image: "https://i.giphy.com/media/FlOHnTIv1mj2U/200w.gif"},
  //     { englishWord: "boil", spanishTranslation: "hervir", rating: 0, image: "https://i.giphy.com/media/6qhETmXwBIogg/200w.gif"},
  //     { englishWord: "remain", spanishTranslation: "permanecer - quedarse", rating: 0, image: "https://i.giphy.com/media/XEo7YJHUeplXa/200w.gif"},
  //     { englishWord: "sigh", spanishTranslation: "suspirar - susurrar", rating: 0, image: "https://i.giphy.com/media/UUcVHqcMwWMcUoNmSN/200w.gif"},
  //     { englishWord: "vacuum", spanishTranslation: "aspirar", rating: 0, image: "https://i.giphy.com/media/cSw9SQuGRjvr2/200w.gif"},
  //     { englishWord: "mind", spanishTranslation: "agregar - importar - preocuparse", rating: 0, image: "https://i.giphy.com/media/ZCqUyl4FbVYqO3xZBW/200w.gif"},
  //     { englishWord: "happen", spanishTranslation: "suceder - ocurrir - pasar", rating: 0, image: "https://i.giphy.com/media/1lxT4sT6Grek6Ma6mW/200w.gif"},
  //     { englishWord: "cry", spanishTranslation: "llorar - gritar", rating: 0, image: "https://i.giphy.com/media/3o6wrvdHFbwBrUFenu/200w.gif"},
  //     { englishWord: "imitate", spanishTranslation: "imitar", rating: 0, image: "https://i.giphy.com/media/3orifcQSbDdACie0Y8/200w.gif"},
  //     { englishWord: "answer", spanishTranslation: "contestar - responder", rating: 0, image: "https://i.giphy.com/media/3o7aD8WTuPv088JAsg/200w.gif"},
  //     { englishWord: "wish", spanishTranslation: "desear", rating: 0, image: "https://i.giphy.com/media/tpTOw6sljB2U/200w.gif"},
  //     { englishWord: "mislay", spanishTranslation: "extraviar - perder", rating: 0, image: "https://i.giphy.com/media/l41lFw057lAJQMwg0/200w.gif"},
  //     { englishWord: "bake", spanishTranslation: "hornear", rating: 0, image: "https://i.giphy.com/media/EQNWSCCJDIGP8U77c7/200w.gif"},
  //     { englishWord: "study", spanishTranslation: "estudiar", rating: 0, image: "https://i.giphy.com/media/S3Pe5NZqgmE8Tl3NI5/200w.gif"},
  //     { englishWord: "absorb", spanishTranslation: "absorber", rating: 0, image: "https://i.giphy.com/media/3oKHWguzCf0ENuevxS/200w.gif"},
  //     { englishWord: "translate", spanishTranslation: "traducir", rating: 0, image: "https://i.giphy.com/media/3o6vXNQiixBMsf4Dra/200w.gif"},
  //     { englishWord: "sew", spanishTranslation: "coser", rating: 0, image: "https://i.giphy.com/media/8Z5H7TFRdlzIuhPKPy/200w.gif"},
  //     { englishWord: "advance", spanishTranslation: "avanzar", rating: 0, image: "https://i.giphy.com/media/xTiN0GwG6QAh1yjzEs/200w.gif"},
  //     { englishWord: "relax", spanishTranslation: "relajar - mitigar", rating: 0, image: "https://i.giphy.com/media/dCG87dWyRNPEgiLQmm/200w.gif"},
  //     { englishWord: "omit", spanishTranslation: "omitir", rating: 0, image: "https://i.giphy.com/media/26uf2EG78j1paWycw/200w.gif"},
  //     { englishWord: "spell", spanishTranslation: "deletrear", rating: 0, image: "https://i.giphy.com/media/w6LzYFWvgn6RQxKH5M/200w.gif"},
  //     { englishWord: "kick", spanishTranslation: "patear - dar punta piés", rating: 0, image: "https://i.giphy.com/media/Ur7br2RDlMlZQzuwUK/200w.gif"},
  //     { englishWord: "plant", spanishTranslation: "plantar - sembrar", rating: 0, image: "https://i.giphy.com/media/4QFBn7Or4Qw43x6qVs/200w.gif"},
  //     { englishWord: "repair", spanishTranslation: "reparar - arreglar", rating: 0, image: "https://i.giphy.com/media/BcJbdfFSsJPwK4O66J/200w.gif"},
  //     { englishWord: "empty", spanishTranslation: "vaciar", rating: 0, image: "https://i.giphy.com/media/Eqz2BTIm1HWrYftdLD/200w.gif"},
  //     { englishWord: "manage", spanishTranslation: "manejar - dirigir - arreglárselas", rating: 0, image: "https://i.giphy.com/media/p2Ow6zI8NbaCeBnpHV/200w.gif"},
  //     { englishWord: "enter", spanishTranslation: "entrar", rating: 0, image: "https://i.giphy.com/media/KIUU4xdCbIA1D24jLu/200w.gif"},
  //     { englishWord: "hate", spanishTranslation: "odiar - aborrecer - detestar", rating: 0, image: "https://i.giphy.com/media/Ol759kRKsQPn2/200w.gif"},
  //     { englishWord: "lick", spanishTranslation: "lamer - adular", rating: 0, image: "https://i.giphy.com/media/iTtFV9jZbc90YLwwJj/200w.gif"},
  //     { englishWord: "touch", spanishTranslation: "tocar - rozar", rating: 0, image: "https://i.giphy.com/media/109RutRrTGY97a/200w.gif"},
  //     { englishWord: "whistle", spanishTranslation: "silbar", rating: 0, image: "https://i.giphy.com/media/9E5wP1RiPvnos/200w.gif"},
  //     { englishWord: "spill", spanishTranslation: "derramar -  regar", rating: 0, image: "https://i.giphy.com/media/SZQBPO4NqHkh6wmdXk/200w.gif"},
  //     { englishWord: "chew", spanishTranslation: "masticar", rating: 0, image: "https://i.giphy.com/media/da17TWjELQ27RpHXds/200w.gif"},
  //     { englishWord: "agree", spanishTranslation: "acordar - estar de acuerdo -  acceder", rating: 0, image: "https://i.giphy.com/media/jN0ygssTH2hoI/200w.gif"},
  //     { englishWord: "bleed", spanishTranslation: "sangrar", rating: 0, image: "https://i.giphy.com/media/QJtiS9rHFqauLNJ5cP/200w.gif"},
  //     { englishWord: "charge", spanishTranslation: "cargar", rating: 0, image: "https://i.giphy.com/media/MdeSslU80bVsTtWxEh/200w.gif"},
  //     { englishWord: "decorate", spanishTranslation: "decorar", rating: 0, image: "https://i.giphy.com/media/3HBTLptQKeJ3UWGRHr/200w.gif"},
  //     { englishWord: "print", spanishTranslation: "imprimir", rating: 0, image: "https://i.giphy.com/media/l2YOxWj7EddS4AZAQ/200w.gif"},
  //     { englishWord: "belong", spanishTranslation: "pertenecer", rating: 0, image: "https://i.giphy.com/media/otMNPSShc61Tu6qAjQ/200w.gif"},
  //     { englishWord: "fasten", spanishTranslation: "abrochar", rating: 0, image: "https://i.giphy.com/media/BouwBuyFhQwlQYBvmG/200w.gif"},
  //     { englishWord: "push", spanishTranslation: "empujar", rating: 0, image: "https://i.giphy.com/media/h7zqTXl02vFPI9BzFo/200w.gif"},
  //     { englishWord: "bother", spanishTranslation: "molestar", rating: 0, image: "https://i.giphy.com/media/5UH2PJ8VIEuMqN8V6R/200w.gif"},
  //     { englishWord: "solve", spanishTranslation: "resolver", rating: 0, image: "https://i.giphy.com/media/vaKfVsu9zseBy/200w.gif"},
  //     { englishWord: "reach", spanishTranslation: "alcanzar - llegar", rating: 0, image: "https://i.giphy.com/media/t8YPf3ACKeouLzEIvr/200w.gif"},
  //     { englishWord: "fear", spanishTranslation: "temer", rating: 0, image: "https://i.giphy.com/media/PaG51G9OKKdKU/200w.gif"},
  //     { englishWord: "appear", spanishTranslation: "aparecer", rating: 0, image: "https://i.giphy.com/media/Tj56evy9oK11BO7Nfi/200w.gif"},
  //     { englishWord: "select", spanishTranslation: "seleccionar", rating: 0, image: "https://i.giphy.com/media/3oxQNm8SjAqNnnIauA/200w.gif"},
  //     { englishWord: "continue", spanishTranslation: "continuar", rating: 0, image: "https://i.giphy.com/media/rcfSXohU0EzOYuRFrK/200w.gif"},
  //     { englishWord: "suppose", spanishTranslation: "suponer", rating: 0, image: "https://i.giphy.com/media/JwkxjWXEZeqRz5Y4QO/200w.gif"},
  //     { englishWord: "camp", spanishTranslation: "acampar", rating: 0, image: "https://i.giphy.com/media/xUPGclNlLxRs6cVfW0/200w.gif"},
  //     { englishWord: "stuff", spanishTranslation: "rellenar", rating: 0, image: "https://i.giphy.com/media/QvwMDYpAMUm6Q/200w.gif"},
  //     { englishWord: "explain", spanishTranslation: "explicar", rating: 0, image: "https://i.giphy.com/media/fqz9cAi3A7a10WyZpO/200w.gif"},
  //     { englishWord: "cheat", spanishTranslation: "engañar", rating: 0, image: "https://i.giphy.com/media/VGb0I0TSOTnkgwhWQ7/200w.gif"},
  //     { englishWord: "receive", spanishTranslation: "recibir", rating: 0, image: "https://i.giphy.com/media/PgoDdQ1yc2aD4yKIWz/200w.gif"},
  //     { englishWord: "fix", spanishTranslation: "arreglar", rating: 0, image: "https://i.giphy.com/media/WQwQnLNj888eaF2wjd/200w.gif"},
  //     { englishWord: "memorize", spanishTranslation: "memorizar", rating: 0, image: "https://i.giphy.com/media/PlxDRCKKUBUd2v80xq/200w.gif"},
  //     { englishWord: "dress", spanishTranslation: "vestir", rating: 0, image: "https://i.giphy.com/media/2xFvdoHiilA4CKmSuX/200w.gif"},
  //     { englishWord: "prepare", spanishTranslation: "preparar", rating: 0, image: "https://i.giphy.com/media/loAGjMfSUfS7eet5Pw/200w.gif"},
  //     { englishWord: "cook", spanishTranslation: "cocinar", rating: 0, image: "https://i.giphy.com/media/rkgX9MTBXJa1O/200w.gif"},
  //     { englishWord: "wrap", spanishTranslation: "envolver - empacar", rating: 0, image: "https://i.giphy.com/media/NsBdKKJmZC84ZXyXIo/200w.gif"},
  //     { englishWord: "identify", spanishTranslation: "identificar", rating: 0, image: "https://i.giphy.com/media/lqA7hJOmjkg7pKW0sF/200w.gif"},
  //     { englishWord: "die", spanishTranslation: "morir", rating: 0, image: "https://i.giphy.com/media/lDPPhStHv9Jfpem7wI/200w.gif"},
  //     { englishWord: "close", spanishTranslation: "cerrar", rating: 0, image: "https://i.giphy.com/media/WspcNpB89fX1UsMx62/200w.gif"},
  //     { englishWord: "stir", spanishTranslation: "revolver - remover ", rating: 0, image: "https://i.giphy.com/media/l0FsyB60ei0yOm3aXz/200w.gif"},
  //     { englishWord: "yawn", spanishTranslation: "bostezar", rating: 0, image: "https://i.giphy.com/media/d5mI2F3MxCTJu/200w.gif"},
  //     { englishWord: "substract", spanishTranslation: "sustraer - restar", rating: 0, image: "https://i.giphy.com/media/bQuYJcZJEHgpRIWvgt/200w.gif"},
  //     { englishWord: "cover", spanishTranslation: "cubrir", rating: 0, image: "https://i.giphy.com/media/ycHWTWR6yIECvb86P8/200w.gif"},
  //     { englishWord: "feed", spanishTranslation: "alimentar(se)", rating: 0, image: "https://i.giphy.com/media/W5Zf6k7mbnMRWnicfg/200w.gif"},
  //     { englishWord: "surround", spanishTranslation: "rodear", rating: 0, image: "https://i.giphy.com/media/3o6Ztn4kP2LiYLI8Ao/200w.gif"},
  //     { englishWord: "publish", spanishTranslation: "publicar", rating: 0, image: "https://i.giphy.com/media/ofkKkFHe0PQu4/200w.gif"},
  //     { englishWord: "persuade", spanishTranslation: "persuadir - convencer", rating: 0, image: "https://i.giphy.com/media/21I909B1Us5hsGiupn/200w.gif"},
  //     { englishWord: "polish", spanishTranslation: "pulir", rating: 0, image: "https://i.giphy.com/media/xUNd9FS6vqnzQIf9Ze/200w.gif"},
  //     { englishWord: "convince", spanishTranslation: "convencer", rating: 0, image: "https://i.giphy.com/media/lSbF6iuzJP3KvN8hzn/200w.gif"},
  //     { englishWord: "drain", spanishTranslation: "drenar - escurrir - agotar", rating: 0, image: "https://i.giphy.com/media/l2QE73NOoVEoEOkWQ/200w.gif"},
  //     { englishWord: "end", spanishTranslation: "terminar", rating: 0, image: "https://i.giphy.com/media/l4pTjOu0NsrLApt0Q/200w.gif"},
  //     { englishWord: "dictate", spanishTranslation: "dictar", rating: 0, image: "https://i.giphy.com/media/zChwZjBl88KNpdRmA2/200w.gif"},
  //     { englishWord: "burn", spanishTranslation: "quemar - incendiar", rating: 0, image: "https://i.giphy.com/media/r9E1WzdMLUQNscbVTm/200w.gif"},
  //     { englishWord: "park", spanishTranslation: "parquear - estacionar", rating: 0, image: "https://i.giphy.com/media/NfY2xu127irrG/200w.gif"},
  //     { englishWord: "mend", spanishTranslation: "remendar - reparar", rating: 0, image: "https://i.giphy.com/media/BcfWCMgzAvrX8qvOmJ/200w.gif"},
  //     { englishWord: "expect", spanishTranslation: "esperar", rating: 0, image: "https://i.giphy.com/media/xT9IgnxYv1zOoxxBTi/200w.gif"},
  //     { englishWord: "borrow", spanishTranslation: "pedir prestado", rating: 0, image: "https://i.giphy.com/media/11zyJuJXMxxJFm/200w.gif"},
  //     { englishWord: "represent", spanishTranslation: "representar", rating: 0, image: "https://i.giphy.com/media/j1XURZ9p4HjaMRdywD/200w.gif"},
  //     { englishWord: "scrub", spanishTranslation: "fregar -  restregar", rating: 0, image: "https://i.giphy.com/media/B1jBJkaYQgaDAsEiZX/200w.gif"},
  //     { englishWord: "smoke", spanishTranslation: "fumar", rating: 0, image: "https://i.giphy.com/media/14qIliCMe87BwA/200w.gif"},
  //     { englishWord: "hurry", spanishTranslation: "apresurar(se)", rating: 0, image: "https://i.giphy.com/media/QVs6OmwbbGvWPJJ75m/200w.gif"},
  //     { englishWord: "smell", spanishTranslation: "oler - husmear", rating: 0, image: "https://i.giphy.com/media/3oEjHXnhx3x2iA5lQY/200w.gif"},
  //     { englishWord: "brown", spanishTranslation: "tostar", rating: 0, image: "https://i.giphy.com/media/QZ8H1uQfTeumErP3sk/200w.gif"},
  //     { englishWord: "dust", spanishTranslation: "desempolvar", rating: 0, image: "https://i.giphy.com/media/3o7buh0sx5p7qrnJ5u/200w.gif"},
  //     { englishWord: "miss", spanishTranslation: "echar de menos -  perder", rating: 0, image: "https://i.giphy.com/media/mOdkhvtXTnnYXjCCZL/200w.gif"},
  //     { englishWord: "drop", spanishTranslation: "bajar - soltar", rating: 0, image: "https://i.giphy.com/media/mD44ZStfDEDngsTL6g/200w.gif"},
  //     { englishWord: "slice", spanishTranslation: "rebanar", rating: 0, image: "https://i.giphy.com/media/l0MYJLrv6NmQx3Eoo/200w.gif"},
  //     { englishWord: "fail", spanishTranslation: "fallar - fracasar - perder", rating: 0, image: "https://i.giphy.com/media/KvTuvZjYiERHy/200w.gif"},
  //     { englishWord: "broil", spanishTranslation: "asar", rating: 0, image: "https://i.giphy.com/media/DC3KWIx4iQXf1ga9o7/200w.gif"},
  //     { englishWord: "land", spanishTranslation: "aterrizar - desembarcar", rating: 0, image: "https://i.giphy.com/media/sDn8Wv2gIDDl3B99d2/200w.gif"},
  //     { englishWord: "trust", spanishTranslation: "confiar - creer", rating: 0, image: "https://i.giphy.com/media/ZzScEDPMnJFp6/200w.gif"},
  //     { englishWord: "pick up", spanishTranslation: "recoger", rating: 0, image: "https://i.giphy.com/media/bocdFeJKj8axPinbsD/200w.gif"},
  //     { englishWord: "try", spanishTranslation: "probar - intentar - ensayar - tratar", rating: 0, image: "https://i.giphy.com/media/8NNDrB5KakH1m/200w.gif"},
  //     { englishWord: "rain", spanishTranslation: "llover", rating: 0, image: "https://i.giphy.com/media/3og0IOUWB5AZoP6la0/200w.gif"},
  //     { englishWord: "clean", spanishTranslation: "limpiar", rating: 0, image: "https://i.giphy.com/media/NHHYRm7mAUQ6Y/200w.gif"},
  //     { englishWord: "wave", spanishTranslation: "agitar - ondear", rating: 0, image: "https://i.giphy.com/media/y9BPgWuDnkKqE5NvwK/200w.gif"},
  //     { englishWord: "call", spanishTranslation: "llamar", rating: 0, image: "https://i.giphy.com/media/VDe02J11N1I7swdREG/200w.gif"},
  //     { englishWord: "pass", spanishTranslation: "pasar - aprobar - superar", rating: 0, image: "https://i.giphy.com/media/l0MYu0z6TH0t4PFII/200w.gif"},
  //     { englishWord: "shed", spanishTranslation: "quitarse - despojarse", rating: 0, image: "https://i.giphy.com/media/jrhSVtLxOKoNEUUTs0/200w.gif"},
  //     { englishWord: "imagine", spanishTranslation: "imaginar", rating: 0, image: "https://i.giphy.com/media/l2JdX9FBRJDg0sdTq/200w.gif"},
  //     { englishWord: "depend", spanishTranslation: "depender", rating: 0, image: "https://i.giphy.com/media/l4pTpbGbC59BbFfSE/200w.gif"},
  //     { englishWord: "comment", spanishTranslation: "comentar", rating: 0, image: "https://i.giphy.com/media/fngcM35fl2ySrblJLV/200w.gif"},
  //     { englishWord: "collect", spanishTranslation: "coleccionar", rating: 0, image: "https://i.giphy.com/media/3o6Mb5mDb7raqYERZC/200w.gif"},
  //     { englishWord: "finish", spanishTranslation: "acabar(con) -  terminar", rating: 0, image: "https://i.giphy.com/media/VQ77RNKX0nyaA/200w.gif"},
  //     { englishWord: "cross", spanishTranslation: "cruzar - atravesar", rating: 0, image: "https://i.giphy.com/media/3oxRmD9a5pLTOOLigM/200w.gif"},
  //     { englishWord: "arrive", spanishTranslation: "llegar", rating: 0, image: "https://i.giphy.com/media/3orif1gluXOV1jIPWU/200w.gif"},
  //     { englishWord: "settle", spanishTranslation: "resolver - llegar a un acuerdo", rating: 0, image: "https://i.giphy.com/media/XnRQH9K6KDqotoQgXe/200w.gif"},
  //     { englishWord: "breed", spanishTranslation: "criar - educar", rating: 0, image: "https://i.giphy.com/media/noHdhIkGHcIhy/200w.gif"},
  //     { englishWord: "declare", spanishTranslation: "declarar", rating: 0, image: "https://i.giphy.com/media/GoqONiCOBhVDRwXxvU/200w.gif"},
  //     { englishWord: "erase", spanishTranslation: "borrar", rating: 0, image: "https://i.giphy.com/media/KD7Ud1YX1nYRkb2r29/200w.gif"},
  //     { englishWord: "sneeze", spanishTranslation: "estornudar", rating: 0, image: "https://i.giphy.com/media/xTk9ZP6AM0EKyQwqNW/200w.gif"},
  //     { englishWord: "multiply", spanishTranslation: "multiplicar", rating: 0, image: "https://i.giphy.com/media/XcFqv8EzBiAlzeEID9/200w.gif"},
  //     { englishWord: "live", spanishTranslation: "vivir", rating: 0, image: "https://i.giphy.com/media/KTqACPHWbIPTLFzgNM/200w.gif"},
  //     { englishWord: "change", spanishTranslation: "cambiar", rating: 0, image: "https://i.giphy.com/media/KcKtC7mz4EHJJPgaXp/200w.gif"},
  //     { englishWord: "save", spanishTranslation: "guardar - ahorrar - salvar", rating: 0, image: "https://i.giphy.com/media/mv2oHmVjhdOK6LFRZX/200w.gif"},
  //     { englishWord: "flunk", spanishTranslation: "fracasar - reprobar", rating: 0, image: "https://i.giphy.com/media/3orieO2nOMDh5kqBoc/200w.gif"},
  //     { englishWord: "promise", spanishTranslation: "prometer", rating: 0, image: "https://i.giphy.com/media/Cu7tfLe1edy3HE7JfC/200w.gif"},
  //     { englishWord: "start", spanishTranslation: "agregar - comenzar - empezar - iniciar", rating: 0, image: "https://i.giphy.com/media/xTiTnmeJ1bBGONMCBy/200w.gif"},
  //     { englishWord: "repeat", spanishTranslation: "repetir", rating: 0, image: "https://i.giphy.com/media/dzvcOaG7QsRd6/200w.gif"},
  //     { englishWord: "invite", spanishTranslation: "invitar", rating: 0, image: "https://i.giphy.com/media/9ses36mVQaH2XBD8Om/200w.gif"},
  //     { englishWord: "want", spanishTranslation: "querer - desear - necesitar", rating: 0, image: "https://i.giphy.com/media/VpGJZP4KlNRQc/200w.gif"},
  //     { englishWord: "fry", spanishTranslation: "freir(se)", rating: 0, image: "https://i.giphy.com/media/41xmKVhZI4Ymfr2rhT/200w.gif"},
  //     { englishWord: "need", spanishTranslation: "necesitar - requerir", rating: 0, image: "https://i.giphy.com/media/nh9k1qzeLf99S/200w.gif"},
  //     { englishWord: "care", spanishTranslation: "cuidar", rating: 0, image: "https://i.giphy.com/media/PCyJu30x3XTIRHyivT/200w.gif"},
  //     { englishWord: "brush", spanishTranslation: "cepillar", rating: 0, image: "https://i.giphy.com/media/dcl7xz9f5RhSw/200w.gif"},
  //     { englishWord: "kill", spanishTranslation: "matar - acabar con", rating: 0, image: "https://i.giphy.com/media/QX26hw37ZXORAWNxyC/200w.gif"},
  //     { englishWord: "complain", spanishTranslation: "quejarse", rating: 0, image: "https://i.giphy.com/media/5uFu5NilveRQ8jBBU2/200w.gif"},
  //     { englishWord: "wonder", spanishTranslation: "preguntarse - asombrarse - maravillarse", rating: 0, image: "https://i.giphy.com/media/872o15eAXFBw66UfNl/200w.gif"},
  //     { englishWord: "skate", spanishTranslation: "patinar", rating: 0, image: "https://i.giphy.com/media/3o6gDYNNm8a2hfzTNe/200w.gif"},
  //     { englishWord: "bathe", spanishTranslation: "bañar", rating: 0, image: "https://i.giphy.com/media/huvuSTprdx9BiBmNYe/200w.gif"},
  //     { englishWord: "walk", spanishTranslation: "caminar - andar - pasear - andar", rating: 0, image: "https://i.giphy.com/media/omHPYZttAVAAw/200w.gif"},
  //     { englishWord: "travel", spanishTranslation: "viajar - andar - recorrer", rating: 0, image: "https://i.giphy.com/media/AErExHJVxRbkm5hPkB/200w.gif"},
  //     { englishWord: "sound", spanishTranslation: "sonar - tocar", rating: 0, image: "https://i.giphy.com/media/JxYcC04MT2Noc/200w.gif"},
  //     { englishWord: "shop", spanishTranslation: "comprar (de tiendas)", rating: 0, image: "https://i.giphy.com/media/3ohs83bO7MKV9koZuE/200w.gif"},
  //     { englishWord: "permit", spanishTranslation: "permitir", rating: 0, image: "https://i.giphy.com/media/tIeCLkB8geYtW/200w.gif"},
  //     { englishWord: "occur", spanishTranslation: "ocurrir - suceder", rating: 0, image: "https://i.giphy.com/media/e3aUKF8Vidrag/200w.gif"},
  //     { englishWord: "clothe", spanishTranslation: "vestir - arropar", rating: 0, image: "https://i.giphy.com/media/1AubIMDoGjnsk/200w.gif"},
  //     { englishWord: "fit", spanishTranslation: "caber - encajar - ajustar", rating: 0, image: "https://i.giphy.com/media/l2Je6sbvJEn1W9OWQ/200w.gif"},
  //     { englishWord: "jump", spanishTranslation: "saltar - brincar", rating: 0, image: "https://i.giphy.com/media/l0HlMhcc67eLP7oeA/200w.gif"},
  //     { englishWord: "name", spanishTranslation: "nombrar - denominar", rating: 0, image: "https://i.giphy.com/media/QWigz8zGygObKfShkF/200w.gif"},
  //   ],
  // },
  {
    name: "Fruits",
    iconName: "nutrition",
    exercises: [
      { englishWord: "apple", spanishTranslation: "manzana", rating: 0, image: null },
      { englishWord: "banana", spanishTranslation: "banano", rating: 0, image: null },
      { englishWord: "orange", spanishTranslation: "naranja", rating: 0, image: null },
      { englishWord: "grape", spanishTranslation: "uva", rating: 0, image: null },
      { englishWord: "strawberry", spanishTranslation: "fresa", rating: 0, image: null },
      { englishWord: "watermelon", spanishTranslation: "sandía", rating: 0, image: null },
      { englishWord: "mango", spanishTranslation: "mango", rating: 0, image: null },
      { englishWord: "pineapple", spanishTranslation: "piña", rating: 0, image: null },
      { englishWord: "kiwi", spanishTranslation: "kiwi", rating: 0, image: null },
      { englishWord: "pear", spanishTranslation: "pera", rating: 0, image: null },
      { englishWord: "coconut", spanishTranslation: "coco", rating: 0, image: null },
      { englishWord: "cherry", spanishTranslation: "cereza", rating: 0, image: null },
      { englishWord: "papaya", spanishTranslation: "papaya", rating: 0, image: null },
      { englishWord: "peach", spanishTranslation: "durazno", rating: 0, image: null },
      { englishWord: "grapefruit", spanishTranslation: "toronja", rating: 0, image: null },
      { englishWord: "plum", spanishTranslation: "ciruela", rating: 0, image: null },
      { englishWord: "apricot", spanishTranslation: "damasco", rating: 0, image: null },
      { englishWord: "guava", spanishTranslation: "guayaba", rating: 0, image: null },
      { englishWord: "fig", spanishTranslation: "higo", rating: 0, image: null },
      { englishWord: "date", spanishTranslation: "dátil", rating: 0, image: null },
    ],
  },
  {
    name: "Colors",
    iconName: "color-palette",
    exercises: [
      { englishWord: "red", spanishTranslation: "rojo", rating: 0, image: null },
      { englishWord: "blue", spanishTranslation: "azul", rating: 0, image: null },
      { englishWord: "green", spanishTranslation: "verde", rating: 0, image: null },
      { englishWord: "yellow", spanishTranslation: "amarillo", rating: 0, image: null },
      { englishWord: "orange", spanishTranslation: "naranja", rating: 0, image: null },
      { englishWord: "purple", spanishTranslation: "púrpura", rating: 0, image: null },
      { englishWord: "pink", spanishTranslation: "rosa", rating: 0, image: null },
      { englishWord: "black", spanishTranslation: "negro", rating: 0, image: null },
      { englishWord: "white", spanishTranslation: "blanco", rating: 0, image: null },
      { englishWord: "gray", spanishTranslation: "gris", rating: 0, image: null },
      { englishWord: "brown", spanishTranslation: "marrón", rating: 0, image: null },
      { englishWord: "gold", spanishTranslation: "dorado", rating: 0, image: null },
      { englishWord: "silver", spanishTranslation: "plateado", rating: 0, image: null },
      { englishWord: "turquoise", spanishTranslation: "turquesa", rating: 0, image: null },
      { englishWord: "violet", spanishTranslation: "violeta", rating: 0, image: null },
      { englishWord: "navy blue", spanishTranslation: "azul marino", rating: 0, image: null },
      { englishWord: "lime green", spanishTranslation: "verde lima", rating: 0, image: null },
      { englishWord: "hot pink", spanishTranslation: "rosa fuerte", rating: 0, image: null },
      { englishWord: "beige", spanishTranslation: "beige", rating: 0, image: null },
      { englishWord: "light blue", spanishTranslation: "azul claro", rating: 0, image: null },
    ],
  },
  {
    name: "Animals",
    iconName: "paw",
    exercises: [
      { englishWord: "dog", spanishTranslation: "perro", rating: 0, image: null },
      { englishWord: "cat", spanishTranslation: "gato", rating: 0, image: null },
      { englishWord: "elephant", spanishTranslation: "elefante", rating: 0, image: null },
      { englishWord: "lion", spanishTranslation: "león", rating: 0, image: null },
      { englishWord: "tiger", spanishTranslation: "tigre", rating: 0, image: null },
      { englishWord: "bear", spanishTranslation: "oso", rating: 0, image: null },
      { englishWord: "monkey", spanishTranslation: "mono", rating: 0, image: null },
      { englishWord: "bird", spanishTranslation: "pájaro", rating: 0, image: null },
      { englishWord: "fish", spanishTranslation: "pez", rating: 0, image: null },
      { englishWord: "snake", spanishTranslation: "serpiente", rating: 0, image: null },
      { englishWord: "frog", spanishTranslation: "rana", rating: 0, image: null },
      { englishWord: "turtle", spanishTranslation: "tortuga", rating: 0, image: null },
      { englishWord: "horse", spanishTranslation: "caballo", rating: 0, image: null },
      { englishWord: "cow", spanishTranslation: "vaca", rating: 0, image: null },
      { englishWord: "pig", spanishTranslation: "cerdo", rating: 0, image: null },
      { englishWord: "sheep", spanishTranslation: "oveja", rating: 0, image: null },
      { englishWord: "chicken", spanishTranslation: "pollo", rating: 0, image: null },
      { englishWord: "mouse", spanishTranslation: "ratón", rating: 0, image: null },
      { englishWord: "rabbit", spanishTranslation: "conejo", rating: 0, image: null },
      { englishWord: "dolphin", spanishTranslation: "delfín", rating: 0, image: null },
    ],
  },
  {
    name: "Family Members",
    iconName: "people",
    exercises: [
      { englishWord: "father", spanishTranslation: "padre", rating: 0, image: null },
      { englishWord: "mother", spanishTranslation: "madre", rating: 0, image: null },
      { englishWord: "son", spanishTranslation: "hijo", rating: 0, image: null },
      { englishWord: "daughter", spanishTranslation: "hija", rating: 0, image: null },
      { englishWord: "grandfather", spanishTranslation: "abuelo", rating: 0, image: null },
      { englishWord: "grandmother", spanishTranslation: "abuela", rating: 0, image: null },
      { englishWord: "brother", spanishTranslation: "hermano", rating: 0, image: null },
      { englishWord: "sister", spanishTranslation: "hermana", rating: 0, image: null },
      { englishWord: "uncle", spanishTranslation: "tío", rating: 0, image: null },
      { englishWord: "aunt", spanishTranslation: "tía", rating: 0, image: null },
      { englishWord: "husband", spanishTranslation: "esposo", rating: 0, image: null },
      { englishWord: "wife", spanishTranslation: "esposa", rating: 0, image: null },
      { englishWord: "cousin (male)", spanishTranslation: "primo", rating: 0, image: null },
      { englishWord: "cousin (female)", spanishTranslation: "prima", rating: 0, image: null },
      { englishWord: "grandson", spanishTranslation: "nieto", rating: 0, image: null },
      { englishWord: "granddaughter", spanishTranslation: "nieta", rating: 0, image: null },
      { englishWord: "stepfather", spanishTranslation: "padrastro", rating: 0, image: null },
      { englishWord: "stepmother", spanishTranslation: "madrastra", rating: 0, image: null },
      { englishWord: "stepson", spanishTranslation: "hijastro", rating: 0, image: null },
      { englishWord: "stepdaughter", spanishTranslation: "hijastra", rating: 0, image: null },
    ],
  },
  // {
  //   name: "Body Parts",
  //   iconName: "body",
  //   exercises: [
  //     { englishWord: "hair", spanishTranslation: "cabello", rating: 0, image: "https://i.giphy.com/media/1wpxKyKAONy98ZhP9G/200w.gif",},
  //               { englishWord: "head", spanishTranslation: "cabeza", rating: 0, image: "https://i.giphy.com/media/NKSq1x79SPTGg/200w.gif",},
  //               { englishWord: "face", spanishTranslation: "rostro", rating: 0, image: "https://i.giphy.com/media/xT1XGyIsUvJNwWfShy/200w.gif",},
  //               { englishWord: "forehead", spanishTranslation: "frente", rating: 0, image: "https://i.giphy.com/media/zb8B5tlJjdpzW/200w.gif",},
  //               { englishWord: "ears", spanishTranslation: "orejas", rating: 0, image: "https://i.giphy.com/media/l4pT6w42S93xNKz2U/200w.gif",},
  //               { englishWord: "eyebrows", spanishTranslation: "cejas", rating: 0, image: "https://i.giphy.com/media/1hA34Uzt3aScCLsZgF/200w.gif",},
  //               { englishWord: "eyelashes", spanishTranslation: "pestañas", rating: 0, image: "https://i.giphy.com/media/bxc12JagLEzrW/200w.gif",},
  //               { englishWord: "eyes", spanishTranslation: "ojos", rating: 0, image: "https://i.giphy.com/media/GQI382aMVej0k/200w.gif",},
  //               { englishWord: "nose", spanishTranslation: "nariz", rating: 0, image: "https://i.giphy.com/media/MNvN8IOC2xd8L5TCNM/200w.gif",},
  //               { englishWord: "mustache", spanishTranslation: "bigote", rating: 0, image: "https://i.giphy.com/media/qSiYwYUlhE5fq/200w.gif",},
  //               { englishWord: "mouth", spanishTranslation: "boca", rating: 0, image: "https://i.giphy.com/media/Lq0h93752f6J9tijrh/200w.gif",},
  //               { englishWord: "lips", spanishTranslation: "labios", rating: 0, image: "https://i.giphy.com/media/jOFIKFiMOz9V6/200w.gif",},
  //               { englishWord: "tongue", spanishTranslation: "lengua", rating: 0, image: "https://i.giphy.com/media/BofJb4WxJnz7jFfxeD/200w.gif",},
  //               { englishWord: "teeth", spanishTranslation: "dientes", rating: 0, image: "https://i.giphy.com/media/l3diGzJhCTx3Ngure/200w.gif",},
  //               { englishWord: "tooth", spanishTranslation: "diente", rating: 0, image: "https://i.giphy.com/media/l3DdGwSucoEG5VNVC/200w.gif",},
  //               { englishWord: "cheeks", spanishTranslation: "mejillas", rating: 0, image: "https://i.giphy.com/media/H1Gd8UC0GjXRUeo6wc/200w.gif",},
  //               { englishWord: "freckles", spanishTranslation: "pecas", rating: 0, image: "https://i.giphy.com/media/LP4TvzUUzZ07LDi4sh/200w.gif",},
  //               { englishWord: "chin", spanishTranslation: "barbilla", rating: 0, image: "https://i.giphy.com/media/1QfiXem2iEi7COEMWt/200w.gif",},
  //               { englishWord: "beard", spanishTranslation: "barba", rating: 0, image: "https://i.giphy.com/media/5ae3ZNBFIwSjK/200w.gif",},
  //               { englishWord: "neck", spanishTranslation: "cuello", rating: 0, image: "https://i.giphy.com/media/UVDF28ep8NJF6/200w.gif",},
  //               { englishWord: "shoulders", spanishTranslation: "hombros", rating: 0, image: "https://i.giphy.com/media/xUA7b0Jb2dIt1NA9jO/200w.gif",},
  //               { englishWord: "armpit", spanishTranslation: "axila", rating: 0, image: "https://i.giphy.com/media/QZ2J1kIdxsGYnR9ska/200w.gif",},
  //               { englishWord: "chest", spanishTranslation: "pecho", rating: 0, image: "https://i.giphy.com/media/xT1XGBVtbsa23KhSb6/200w.gif",},
  //               { englishWord: "breasts", spanishTranslation: "senos", rating: 0, image: "https://i.giphy.com/media/gQ2fLEOtl4F5m/200w.gif",},
  //               { englishWord: "abdomen", spanishTranslation: "abdomen", rating: 0, image: "https://i.giphy.com/media/l1ugn5yDMJDNfmJZC/200w.gif",},
  //               { englishWord: "belly", spanishTranslation: "vientre", rating: 0, image: "https://i.giphy.com/media/zUW23b6FmzB5e/200w.gif",},
  //               { englishWord: "hips", spanishTranslation: "cadera", rating: 0, image: "https://i.giphy.com/media/3bqSbktO7KcQU/200w.gif",},
  //               { englishWord: "waist", spanishTranslation: "cintura", rating: 0, image: "https://i.giphy.com/media/WhoNNhPTSgNkA/200w.gif",},
  //               { englishWord: "belly button", spanishTranslation: "ombligo", rating: 0, image: "https://i.giphy.com/media/3oKHWkwJK8Ibu490xa/200w.gif",},
  //               { englishWord: "back", spanishTranslation: "espalda", rating: 0, image: "https://i.giphy.com/media/mqjnXsqlSmrFJDjpNM/200w.gif",},
  //               { englishWord: "buttocks", spanishTranslation: "glúteos", rating: 0, image: "https://i.giphy.com/media/YP74iVhXjrZmWPqb6d/200w.gif",},
  //               { englishWord: "arms", spanishTranslation: "brazos", rating: 0, image: "https://i.giphy.com/media/jQbKNjpx4r5cxqEuPb/200w.gif",},
  //               { englishWord: "elbow", spanishTranslation: "codo", rating: 0, image: "https://i.giphy.com/media/e3WzjGpaanMm4/200w.gif",},
  //               { englishWord: "forearm", spanishTranslation: "antebrazo", rating: 0, image: "https://i.giphy.com/media/cZDmWv5SjMdZwhMf1M/200w.gif",},
  //               { englishWord: "wrist", spanishTranslation: "muñeca", rating: 0, image: "https://i.giphy.com/media/gq9SPDGxZtxaI7kQnO/200w.gif",},
  //               { englishWord: "fist", spanishTranslation: "puño", rating: 0, image: "https://i.giphy.com/media/WoF3yfYupTt8mHc7va/200w.gif",},
  //               { englishWord: "hand", spanishTranslation: "mano", rating: 0, image: "https://i.giphy.com/media/UQVIhXZpCS17U3U4xR/200w.gif",},
  //               { englishWord: "fingers", spanishTranslation: "dedos", rating: 0, image: "https://i.giphy.com/media/3o72EUwmrRFtyT1Vhm/200w.gif",},
  //               { englishWord: "knuckles", spanishTranslation: "nudillos", rating: 0, image: "https://i.giphy.com/media/4ttCTXSeAu0GSXy9h5/200w.gif",},
  //               { englishWord: "nails", spanishTranslation: "uñas", rating: 0, image: "https://i.giphy.com/media/l8OrHJlaGTEsM/200w.gif",},
  //               { englishWord: "legs", spanishTranslation: "piernas", rating: 0, image: "https://i.giphy.com/media/KxYYj1sXfvve8/200w.gif",},
  //               { englishWord: "thigh", spanishTranslation: "muslo", rating: 0, image: "https://i.giphy.com/media/X0iEaPoda9Ps2nhbgO/200w.gif",},
  //               { englishWord: "knees", spanishTranslation: "rodillas", rating: 0, image: "https://i.giphy.com/media/l2JejHs0YIAUpcAWQ/200w.gif",},
  //               { englishWord: "foot", spanishTranslation: "pie", rating: 0, image: "https://i.giphy.com/media/loHIRKRjn6Nu2Xixbw/200w.gif",},
  //               { englishWord: "feet", spanishTranslation: "pies", rating: 0, image: "https://i.giphy.com/media/3o7WIucW89bVVGgsIE/200w.gif",},
  //               { englishWord: "ankle", spanishTranslation: "tobillo", rating: 0, image: "https://i.giphy.com/media/5AwCyyagCgqX77tsyK4/200w.gif",},
  //               { englishWord: "heel", spanishTranslation: "talón", rating: 0, image: "https://i.giphy.com/media/FWTbmJb6SG55C/200w.gif",},
  //               { englishWord: "skull", spanishTranslation: "cráneo", rating: 0, image: "https://i.giphy.com/media/r1L9IlkeMbKoyJrMtm/200w.gif",},
  //               { englishWord: "brain", spanishTranslation: "cerebro", rating: 0, image: "https://i.giphy.com/media/l41m04gr7tRet7Uas/200w.gif",},
  //               { englishWord: "throat", spanishTranslation: "garganta", rating: 0, image: "https://i.giphy.com/media/U7LqpyMWtoeSXayium/200w.gif",},
  //               { englishWord: "ribs", spanishTranslation: "costillas", rating: 0, image: "https://i.giphy.com/media/3o6Zt6FgqP2HYRJ47m/200w.gif",},
  //               { englishWord: "heart", spanishTranslation: "corazón", rating: 0, image: "https://i.giphy.com/media/ZOStzpF9H5syI/200w.gif",},
  //               { englishWord: "lungs", spanishTranslation: "pulmones", rating: 0, image: "https://i.giphy.com/media/YImJMKZwMYsOk/200w.gif",},
  //               { englishWord: "stomach", spanishTranslation: "estómago", rating: 0, image: "https://i.giphy.com/media/9C2hzbt5VUnJ85ldZ0/200w.gif",},
  //               { englishWord: "blood", spanishTranslation: "sangre", rating: 0, image: "https://i.giphy.com/media/UGGe8BBrkuAUM/200w.gif",},
  //               { englishWord: "bones", spanishTranslation: "huesos", rating: 0, image: "https://i.giphy.com/media/14p7smEhLwMHD2/200w.gif",},
  //               { englishWord: "muscles", spanishTranslation: "músculos", rating: 0, image: "https://i.giphy.com/media/BCIoXfA95d1ba/200w.gif",},
  //               { englishWord: "skeleton", spanishTranslation: "esqueleto", rating: 0, image: "https://i.giphy.com/media/3ohhwfAa9rbXaZe86c/200w.gif",},
  //               { englishWord: "skin", spanishTranslation: "piel", rating: 0, image: "https://i.giphy.com/media/9AXvu1JYGPrSU/200w.gif",},
  //               { englishWord: "veins", spanishTranslation: "venas", rating: 0, image: "https://i.giphy.com/media/8qrmcwwJnW5XaLJQUB/200w.gif",}
  //   ],
  // },
  {
    name: "Clothing",
    iconName: "shirt",
    exercises: [
      { englishWord: "shirt", spanishTranslation: "camisa", rating: 0, image: null },
      { englishWord: "pants", spanishTranslation: "pantalones", rating: 0, image: null },
      { englishWord: "dress", spanishTranslation: "vestido", rating: 0, image: null },
      { englishWord: "skirt", spanishTranslation: "falda", rating: 0, image: null },
      { englishWord: "shorts", spanishTranslation: "cortos", rating: 0, image: null },
      { englishWord: "shoes", spanishTranslation: "zapatos", rating: 0, image: null },
      { englishWord: "socks", spanishTranslation: "calcetines", rating: 0, image: null },
      { englishWord: "hat", spanishTranslation: "sombrero", rating: 0, image: null },
      { englishWord: "jacket", spanishTranslation: "chaqueta", rating: 0, image: null },
      { englishWord: "coat", spanishTranslation: "abrigo", rating: 0, image: null },
      { englishWord: "underwear", spanishTranslation: "ropa interior", rating: 0, image: null },
      { englishWord: "gloves", spanishTranslation: "guantes", rating: 0, image: null },
      { englishWord: "scarf", spanishTranslation: "bufanda", rating: 0, image: null },
      { englishWord: "tie", spanishTranslation: "corbata", rating: 0, image: null },
      { englishWord: "belt", spanishTranslation: "cinturón", rating: 0, image: null },
      { englishWord: "pajamas", spanishTranslation: "pijama", rating: 0, image: null },
      { englishWord: "sunglasses", spanishTranslation: "gafas de sol", rating: 0, image: null },
      { englishWord: " swimsuit", spanishTranslation: "traje de baño", rating: 0, image: null },
      { englishWord: "dress shirt", spanishTranslation: "camisa de vestir", rating: 0, image: null },
      { englishWord: "t-shirt", spanishTranslation: "camiseta", rating: 0, image: null },
    ],
  },
  {
    name: "Professions",
    iconName: "briefcase",
    exercises: [
      { englishWord: "doctor", spanishTranslation: "doctor", rating: 0, image: null },
      { englishWord: "teacher", spanishTranslation: "profesor", rating: 0, image: null },
      { englishWord: "nurse", spanishTranslation: "enfermera", rating: 0, image: null },
      { englishWord: "engineer", spanishTranslation: "ingeniero", rating: 0, image: null },
      { englishWord: "lawyer", spanishTranslation: "abogado", rating: 0, image: null },
      { englishWord: "police officer", spanishTranslation: "oficial de policía", rating: 0, image: null },
      { englishWord: "firefighter", spanishTranslation: "bombero", rating: 0, image: null },
      { englishWord: "dentist", spanishTranslation: "dentista", rating: 0, image: null },
      { englishWord: "architect", spanishTranslation: "arquitecto", rating: 0, image: null },
      { englishWord: "writer", spanishTranslation: "escritor", rating: 0, image: null },
      { englishWord: "artist", spanishTranslation: "artista", rating: 0, image: null },
      { englishWord: "musician", spanishTranslation: "músico", rating: 0, image: null },
      { englishWord: "athlete", spanishTranslation: "atleta", rating: 0, image: null },
      { englishWord: "programmer", spanishTranslation: "programador", rating: 0, image: null },
      { englishWord: "accountant", spanishTranslation: "contador", rating: 0, image: null },
      { englishWord: "secretary", spanishTranslation: "secretaria", rating: 0, image: null },
      { englishWord: "chef", spanishTranslation: "chef", rating: 0, image: null },
      { englishWord: "waiter/waitress", spanishTranslation: "mesero/mesera", rating: 0, image: null },
      { englishWord: " hairstylist", spanishTranslation: "peluquero", rating: 0, image: null },
      { englishWord: "mechanic", spanishTranslation: "mecánico", rating: 0, image: null },
    ],
  },
  {
    name: "Transportation",
    iconName: "bus",
    exercises: [
      { englishWord: "car", spanishTranslation: "carro", rating: 0, image: null },
      { englishWord: "bus", spanishTranslation: "autobús", rating: 0, image: null },
      { englishWord: "train", spanishTranslation: "tren", rating: 0, image: null },
      { englishWord: "airplane", spanishTranslation: "avión", rating: 0, image: null },
      { englishWord: "bicycle", spanishTranslation: "bicicleta", rating: 0, image: null },
      { englishWord: "motorcycle", spanishTranslation: "motocicleta", rating: 0, image: null },
      { englishWord: "boat", spanishTranslation: "bote", rating: 0, image: null },
      { englishWord: "ship", spanishTranslation: "barco", rating: 0, image: null },
      { englishWord: "taxi", spanishTranslation: "taxi", rating: 0, image: null },
      { englishWord: "subway", spanishTranslation: "metro", rating: 0, image: null },
      { englishWord: "truck", spanishTranslation: "camión", rating: 0, image: null },
      { englishWord: "scooter", spanishTranslation: "patinete", rating: 0, image: null },
      { englishWord: "helicopter", spanishTranslation: "helicóptero", rating: 0, image: null },
      { englishWord: "hot air balloon", spanishTranslation: "globo aerostático", rating: 0, image: null },
      { englishWord: "ferry", spanishTranslation: "ferry", rating: 0, image: null },
      { englishWord: "cable car", spanishTranslation: "teleférico", rating: 0, image: null },
      { englishWord: "tram", spanishTranslation: "tranvía", rating: 0, image: null },
      { englishWord: "rickshaw", spanishTranslation: "rickshaw", rating: 0, image: null },
      { englishWord: "skateboard", spanishTranslation: "patineta", rating: 0, image: null },
      { englishWord: "rollerblades", spanishTranslation: "patines en línea", rating: 0, image: null },
    ],
  },
  {
    name: "Weather",
    iconName: "partly-sunny",
    exercises: [
      { englishWord: "sunny", spanishTranslation: "soleado", rating: 0, image: null },
      { englishWord: "cloudy", spanishTranslation: "nublado", rating: 0, image: null },
      { englishWord: "rainy", spanishTranslation: "lluvioso", rating: 0, image: null },
      { englishWord: "snowy", spanishTranslation: "nevado", rating: 0, image: null },
      { englishWord: "windy", spanishTranslation: "ventoso", rating: 0, image: null },
      { englishWord: "stormy", spanishTranslation: "tormentoso", rating: 0, image: null },
      { englishWord: "hot", spanishTranslation: "caliente", rating: 0, image: null },
      { englishWord: "cold", spanishTranslation: "frío", rating: 0, image: null },
      { englishWord: "humid", spanishTranslation: "húmedo", rating: 0, image: null },
      { englishWord: "dry", spanishTranslation: "seco", rating: 0, image: null },
      { englishWord: "foggy", spanishTranslation: "neblinoso", rating: 0, image: null },
      { englishWord: "clear", spanishTranslation: "claro", rating: 0, image: null },
      { englishWord: "overcast", spanishTranslation: "cubierto", rating: 0, image: null },
      { englishWord: "breezy", spanishTranslation: "ventoso", rating: 0, image: null },
      { englishWord: "hazy", spanishTranslation: "brumoso", rating: 0, image: null },
      { englishWord: "thunderstorm", spanishTranslation: "tormenta eléctrica", rating: 0, image: null },
      { englishWord: "blizzard", spanishTranslation: "tormenta de nieve", rating: 0, image: null },
      { englishWord: "hurricane", spanishTranslation: "huracán", rating: 0, image: null },
      { englishWord: "tornado", spanishTranslation: "tornado", rating: 0, image: null },
      { englishWord: "rainbow", spanishTranslation: "arcoíris", rating: 0, image: null },
    ],
  },
  {
    name: "WH Questions",
    iconName: "help",
    exercises: [
      { englishWord: "who", spanishTranslation: "¿Quién?", rating: 0, image: "https://i.giphy.com/media/xT9DPsaooCwWMHyydO/200w.gif",},
      { englishWord: "what", spanishTranslation: "¿Qué ?", rating: 0, image: "https://i.giphy.com/media/iFxaWHoUsXqm6ej3zp/200w.gif",},
      { englishWord: "what", spanishTranslation: "¿Cuál? (opciones desconocidas)", rating: 0, image: "https://i.giphy.com/media/iFxaWHoUsXqm6ej3zp/200w.gif",},
      { englishWord: "when", spanishTranslation: "¿Cuándo?", rating: 0, image: "https://i.giphy.com/media/fUwOs80ja3sTPpjndh/200w.gif",},
      { englishWord: "why", spanishTranslation: "¿Por qué?", rating: 0, image: "https://i.giphy.com/media/5BWVeEbJsaB4UZAzSz/200w.gif",},
      { englishWord: "where", spanishTranslation: "¿Dónde?", rating: 0, image: "https://i.giphy.com/media/26ni7e85ldigoAvK0/200w.gif",},
      { englishWord: "whose", spanishTranslation: "¿De quién?", rating: 0, image: "https://i.giphy.com/media/3o7bu1Q2WGULpXCUNy/200w.gif",},
      { englishWord: "which", spanishTranslation: "¿Cuál? (opciones conocidas)", rating: 0, image: "https://i.giphy.com/media/lx7AtejahSmgIWmLX5/200w.gif",},
      { englishWord: "how", spanishTranslation: "¿Cómo?", rating: 0, image: "https://i.giphy.com/media/26mkhPIN0KxjxfPbi/200w.gif",},
      { englishWord: "how old", spanishTranslation: "¿Qué edad?", rating: 0, image: "https://i.giphy.com/media/VO1qsPmPvwLmhxNalE/200w.gif",},
      { englishWord: "how often", spanishTranslation: "¿Con qué frecuencia?", rating: 0, image: "https://i.giphy.com/media/xT5LMVwj6YcQarnVPa/200w.gif",},
      { englishWord: "how fast", spanishTranslation: "¿Qué tan rapido?", rating: 0, image: "https://i.giphy.com/media/KKBpCeK0ASoPS/200w.gif",},
      { englishWord: "how long", spanishTranslation: "¿Cuánto tiempo?", rating: 0, image: "https://i.giphy.com/media/GJpJJPfhcoDl0xOZXI/200w.gif",},
      { englishWord: "how many", spanishTranslation: "¿Cuántos(as)? (contable)", rating: 0, image: "https://i.giphy.com/media/j5ra3QdLthGSPtjmqz/200w.gif",},
      { englishWord: "how much", spanishTranslation: "¿Cuántos(as)? (incontable)", rating: 0, image: "https://i.giphy.com/media/LScY2HbrHCICWKrUbO/200w.gif",},
      { englishWord: "how well", spanishTranslation: "¿Qué tan bien?", rating: 0, image: "https://i.giphy.com/media/JkiqsyCzZmRLqBuwJ8/200w.gif",},
      { englishWord: "how tall", spanishTranslation: "¿Cuánto mide?", rating: 0, image: "https://i.giphy.com/media/ZeF8zmEwCKH1F8qN9O/200w.gif",},
      { englishWord: "how far", spanishTranslation: "¿Qué tan lejos?", rating: 0, image: "https://i.giphy.com/media/xnsFqNS2g4NIzKbM58/200w.gif",}
 
    ],
  },
  {
    name: "Days of the Week",
    iconName: "calendar",
    exercises: [
      { englishWord: "Monday", spanishTranslation: "lunes", rating: 0, image: null },
      { englishWord: "Tuesday", spanishTranslation: "martes", rating: 0, image: null },
      { englishWord: "Wednesday", spanishTranslation: "miércoles", rating: 0, image: null },
      { englishWord: "Thursday", spanishTranslation: "jueves", rating: 0, image: null },
      { englishWord: "Friday", spanishTranslation: "viernes", rating: 0, image: null },
      { englishWord: "Saturday", spanishTranslation: "sábado", rating: 0, image: null },
      { englishWord: "Sunday", spanishTranslation: "domingo", rating: 0, image: null },
    ],
  },
  {
    name: "Months of the Year",
    iconName: "calendar",
    exercises: [
      { englishWord: "January", spanishTranslation: "enero", rating: 0, image: null },
      { englishWord: "February", spanishTranslation: "febrero", rating: 0, image: null },
      { englishWord: "March", spanishTranslation: "marzo", rating: 0, image: null },
      { englishWord: "April", spanishTranslation: "abril", rating: 0, image: null },
      { englishWord: "May", spanishTranslation: "mayo", rating: 0, image: null },
      { englishWord: "June", spanishTranslation: "junio", rating: 0, image: null },
      { englishWord: "July", spanishTranslation: "julio", rating: 0, image: null },
      { englishWord: "August", spanishTranslation: "agosto", rating: 0, image: null },
      { englishWord: "September", spanishTranslation: "septiembre", rating: 0, image: null },
      { englishWord: "October", spanishTranslation: "octubre", rating: 0, image: null },
      { englishWord: "November", spanishTranslation: "noviembre", rating: 0, image: null },
      { englishWord: "December", spanishTranslation: "diciembre", rating: 0, image: null },
    ],
  },
  {
    name: "Food and Drinks",
    iconName: "restaurant",
    exercises: [
      { englishWord: "pizza", spanishTranslation: "pizza", rating: 0, image: null },
      { englishWord: "hamburger", spanishTranslation: "hamburguesa", rating: 0, image: null },
      { englishWord: "pasta", spanishTranslation: "pasta", rating: 0, image: null },
      { englishWord: "chicken", spanishTranslation: "pollo", rating: 0, image: null },
      { englishWord: "fish", spanishTranslation: "pescado", rating: 0, image: null },
      { englishWord: "rice", spanishTranslation: "arroz", rating: 0, image: null },
      { englishWord: "bread", spanishTranslation: "pan", rating: 0, image: null },
      { englishWord: "salad", spanishTranslation: "ensalada", rating: 0, image: null },
      { englishWord: "soup", spanishTranslation: "sopa", rating: 0, image: null },
      { englishWord: "fruits", spanishTranslation: "frutas", rating: 0, image: null }, 
      { englishWord: "vegetables", spanishTranslation: "verduras", rating: 0, image: null }, 
      { englishWord: "coffee", spanishTranslation: "café", rating: 0, image: null },
      { englishWord: "tea", spanishTranslation: "té", rating: 0, image: null },
      { englishWord: "juice", spanishTranslation: "jugo", rating: 0, image: null },
      { englishWord: "water", spanishTranslation: "agua", rating: 0, image: null },
      { englishWord: "milk", spanishTranslation: "leche", rating: 0, image: null },
      { englishWord: "soda", spanishTranslation: "refresco", rating: 0, image: null },
      { englishWord: "wine", spanishTranslation: "vino", rating: 0, image: null },
      { englishWord: "beer", spanishTranslation: "cerveza", rating: 0, image: null },
      { englishWord: "chocolate", spanishTranslation: "chocolate", rating: 0, image: null },
    ],
  },
  {
    name: "Household Items",
    iconName: "home",
    exercises: [
      { englishWord: "chair", spanishTranslation: "silla", rating: 0, image: null },
      { englishWord: "table", spanishTranslation: "mesa", rating: 0, image: null },
      { englishWord: "bed", spanishTranslation: "cama", rating: 0, image: null },
      { englishWord: "couch", spanishTranslation: "sofá", rating: 0, image: null },
      { englishWord: "television", spanishTranslation: "televisión", rating: 0, image: null },
      { englishWord: "refrigerator", spanishTranslation: "refrigerador", rating: 0, image: null },
      { englishWord: "stove", spanishTranslation: "estufa", rating: 0, image: null },
      { englishWord: "microwave", spanishTranslation: "microondas", rating: 0, image: null },
      { englishWord: "vacuum cleaner", spanishTranslation: "aspiradora", rating: 0, image: null },
      { englishWord: "washing machine", spanishTranslation: "lavadora", rating: 0, image: null },
      { englishWord: "dryer", spanishTranslation: "secadora", rating: 0, image: null },
      { englishWord: "lamp", spanishTranslation: "lámpara", rating: 0, image: null },
      { englishWord: "curtain", spanishTranslation: "cortina", rating: 0, image: null },
      { englishWord: "rug", spanishTranslation: "alfombra", rating: 0, image: null },
      { englishWord: "shelf", spanishTranslation: "estantería", rating: 0, image: null },
      { englishWord: "cabinet", spanishTranslation: "armario", rating: 0, image: null },
      { englishWord: "trash can", spanishTranslation: "bote de basura", rating: 0, image: null },
      { englishWord: "fork", spanishTranslation: "tenedor", rating: 0, image: null },
      { englishWord: "spoon", spanishTranslation: "cuchara", rating: 0, image: null },
      { englishWord: "knife", spanishTranslation: "cuchillo", rating: 0, image: null },
    ],
  },
  {
    name: "School Supplies",
    iconName: "school",
    exercises: [
      { englishWord: "backpack", spanishTranslation: "mochila", rating: 0, image: null },
      { englishWord: "notebook", spanishTranslation: "cuaderno", rating: 0, image: null },
      { englishWord: "pencil", spanishTranslation: "lápiz", rating: 0, image: null },
      { englishWord: "pen", spanishTranslation: "bolígrafo", rating: 0, image: null },
      { englishWord: "eraser", spanishTranslation: "borrador", rating: 0, image: null },
      { englishWord: "crayon", spanishTranslation: "crayón", rating: 0, image: null },
      { englishWord: "marker", spanishTranslation: "marcador", rating: 0, image: null },
      { englishWord: "highlighter", spanishTranslation: "marcador fluorescente", rating: 0, image: null },
      { englishWord: "scissors", spanishTranslation: "tijeras", rating: 0, image: null },
      { englishWord: "glue", spanishTranslation: "pegamento", rating: 0, image: null },
      { englishWord: "tape", spanishTranslation: "cinta adhesiva", rating: 0, image: null },
      { englishWord: "ruler", spanishTranslation: "regla", rating: 0, image: null },
      { englishWord: "calculator", spanishTranslation: "calculadora", rating: 0, image: null },
      { englishWord: "binder", spanishTranslation: "carpeta", rating: 0, image: null },
      { englishWord: "folder", spanishTranslation: "carpeta", rating: 0, image: null },
      { englishWord: "colored pencils", spanishTranslation: "lápices de colores", rating: 0, image: null },
      { englishWord: "paper clips", spanishTranslation: "clips", rating: 0, image: null },
      { englishWord: "stapler", spanishTranslation: "engrapadora", rating: 0, image: null },
      { englishWord: "protractor", spanishTranslation: "transportador", rating: 0, image: null },
      { englishWord: "compass", spanishTranslation: "compás", rating: 0, image: null },
    ],
  },
  {
    name: "Sports",
    iconName: "football",
    exercises: [
      { englishWord: "Soccer", spanishTranslation: "fútbol", rating: 0, image: " εικόνα ποδοσφαίρου [image of Soccer ball]"},
      { englishWord: "Basketball", spanishTranslation: "baloncesto", rating: 0, image: " [image of Basketball ball]"},
      { englishWord: "Baseball", spanishTranslation: "béisbol", rating: 0, image: " [image of Baseball ball]"},
      { englishWord: "American Football", spanishTranslation: "fútbol americano", rating: 0, image: " [image of American football ball]"},
      { englishWord: "Tennis", spanishTranslation: "tenis", rating: 0, image: " [image of Tennis ball]"},
      { englishWord: "Volleyball", spanishTranslation: "voleibol", rating: 0, image: " [image of Volleyball ball]"},
      { englishWord: "Hockey", spanishTranslation: "hockey sobre hielo", rating: 0, image: " [image of Hockey puck]"},
      { englishWord: "Cricket", spanishTranslation: "grillo", rating: 0, image: " [image of Cricket ball]"},
      { englishWord: "Badminton", spanishTranslation: "bádminton", rating: 0, image: " [image of Badminton birdie]"},
      { englishWord: "Golf", spanishTranslation: "golf", rating: 0, image: " [image of Golf ball]"},
      { englishWord: "Swimming", spanishTranslation: "natación", rating: 0, image: " [image of swimmer]"},
      { englishWord: "Cycling", spanishTranslation: "ciclismo", rating: 0, image: " [image of bicycle]"},
      { englishWord: "Running", spanishTranslation: "correr", rating: 0, image: " [image of runner]"},
      { englishWord: "Weightlifting", spanishTranslation: "levantamiento de pesas", rating: 0, image: " [image of weightlifter]"},
      { englishWord: "Gymnastics", spanishTranslation: "gimnasia", rating: 0, image: " [image of gymnast]"},
      { englishWord: "Martial Arts", spanishTranslation: "artes marciales", rating: 0, image: " [image of martial artist]"},
      { englishWord: "Yoga", spanishTranslation: "yoga", rating: 0, image: " [image of yoga person]"},
      { englishWord: "Dance", spanishTranslation: "bailar", rating: 0, image: " [image of dancer]"},
      { englishWord: "Rock Climbing", spanishTranslation: "escalada", rating: 0, image: " [image of rock climber]"},
      { englishWord: "Horseback Riding", spanishTranslation: "equitación", rating: 0, image: " [image of horseback rider]"},
    ],
  },
  {
    name: "Hobbies",
    iconName: "brush",
    exercises: [
      { englishWord: "Drawing", spanishTranslation: "dibujar", rating: 0, image: null },
      { englishWord: "Painting", spanishTranslation: "pintar", rating: 0, image: null },
      { englishWord: "Playing music", spanishTranslation: "tocar música", rating: 0, image: null },
      { englishWord: "Singing", spanishTranslation: "cantar", rating: 0, image: null },
      { englishWord: "Playing an instrument", spanishTranslation: "tocar un instrumento", rating: 0, image: null },
      { englishWord: "Writing", spanishTranslation: "escribir", rating: 0, image: null },
      { englishWord: "Reading", spanishTranslation: "leer", rating: 0, image: null },
      { englishWord: "Photography", spanishTranslation: "fotografía", rating: 0, image: null },
      { englishWord: "Cooking", spanishTranslation: "cocinar", rating: 0, image: null },
      { englishWord: "Baking", spanishTranslation: "hornear", rating: 0, image: null },
      { englishWord: "Gardening", spanishTranslation: "jardinería", rating: 0, image: null },
      { englishWord: "Hiking", spanishTranslation: "senderismo", rating: 0, image: null },
      { englishWord: "Camping", spanishTranslation: "acampar", rating: 0, image: null },
      { englishWord: "Traveling", spanishTranslation: "viajar", rating: 0, image: null },
      { englishWord: "Learning a new language", spanishTranslation: "aprender un nuevo idioma", rating: 0, image: null },
      { englishWord: "Playing video games", spanishTranslation: "jugar videojuegos", rating: 0, image: null },
      { englishWord: "Crafting", spanishTranslation: "manualidades", rating: 0, image: null },
      { englishWord: "Playing board games", spanishTranslation: "jugar juegos de mesa", rating: 0, image: null },
      { englishWord: "Volunteering", spanishTranslation: "voluntariado", rating: 0, image: null },
      { englishWord: "Watching movies", spanishTranslation: "ver películas", rating: 0, image: null },
    ],
  },
  {
    name: "Emotions",
    iconName: "happy",
    exercises: [
      { englishWord: "Happy", spanishTranslation: "feliz", rating: 0, image: null },
      { englishWord: "Sad", spanishTranslation: "triste", rating: 0, image: null },
      { englishWord: "Angry", spanishTranslation: "enojado/a", rating: 0, image: null },
      { englishWord: "Excited", spanishTranslation: "emocionado/a", rating: 0, image: null },
      { englishWord: "Scared", spanishTranslation: "asustado/a", rating: 0, image: null },
      { englishWord: "Surprised", spanishTranslation: "sorprendido/a", rating: 0, image: null },
      { englishWord: "Worried", spanishTranslation: "preocupado/a", rating: 0, image: null },
      { englishWord: "Confused", spanishTranslation: "confundido/a", rating: 0, image: null },
      { englishWord: "Bored", spanishTranslation: "aburrido/a", rating: 0, image: null },
      { englishWord: "Frustrated", spanishTranslation: "frustrado/a", rating: 0, image: null },
      { englishWord: "Hopeful", spanishTranslation: "esperanzado/a", rating: 0, image: null },
      { englishWord: "Grateful", spanishTranslation: "agradecido/a", rating: 0, image: null },
      { englishWord: "Proud", spanishTranslation: "orgulloso/a", rating: 0, image: null },
      { englishWord: "Embarrassed", spanishTranslation: "avergonzado/a", rating: 0, image: null },
      { englishWord: "Calm", spanishTranslation: "calmado/a", rating: 0, image: null },
      { englishWord: "Relaxed", spanishTranslation: "relajado/a", rating: 0, image: null },
      { englishWord: "In love", spanishTranslation: "enamorado/a", rating: 0, image: null },
      { englishWord: "Jealous", spanishTranslation: "celoso/a", rating: 0, image: null },
      { englishWord: "Disappointed", spanishTranslation: "decepcionado/a", rating: 0, image: null },
      { englishWord: "Angry (informal)", spanishTranslation: "enfadado/a", rating: 0, image: null }, // Note: enfadado is a more informal way to say angry in Spanish.
    ],
  },
  // {
  //   name: "Irregular Verbs",
  //   iconName: "happy",
  //   exercises: [
  //     { englishWord: "rise, rose, risen", spanishTranslation: "subir - ascender", rating: 0, image: " https://i.giphy.com/media/kKkxK0OAb8kLrEtLew/200w.gif",},
  //     { englishWord: "flee, fled, fled", spanishTranslation: "evitar - huir de", rating: 0, image: " https://i.giphy.com/media/S3PjeN6iPYyxJYvdji/200w.gif",},
  //     { englishWord: "befall, befell, befallen", spanishTranslation: "suceder - acontecer - ocurrir", rating: 0, image: " https://i.giphy.com/media/eg40fWsnGDKSwzZ9JM/200w.gif",},
  //     { englishWord: "wear, wore, worn", spanishTranslation: "usar - llevar puesto", rating: 0, image: " https://i.giphy.com/media/sMTz9zCVqkzU4/200w.gif",},
  //     { englishWord: "put, put, put", spanishTranslation: "poner - colocar", rating: 0, image: " https://i.giphy.com/media/26tk0bT7b5j9eihyg/200w.gif",},
  //     { englishWord: "bid, bid, bid", spanishTranslation: "mandar - ordenar", rating: 0, image: " https://i.giphy.com/media/clnMyAMF1Enzf3Mrh2/200w.gif",},
  //     { englishWord: "grind, ground, ground", spanishTranslation: "moler - triturar", rating: 0, image: " https://i.giphy.com/media/Ie3nZAD9A6fOe47mum/200w.gif",},
  //     { englishWord: "split, split, split", spanishTranslation: "dividirse - partir", rating: 0, image: " https://i.giphy.com/media/O1I2B29viaEhuWT01R/200w.gif",},
  //     { englishWord: "send, sent, sent", spanishTranslation: "enviar - mandar", rating: 0, image: " https://i.giphy.com/media/1BgqNZwAfxiiMN3vsT/200w.gif",},
  //     { englishWord: "go, went, gone", spanishTranslation: "ir", rating: 0, image: " https://i.giphy.com/media/69zJi6jaJtYpRHZwd6/200w.gif",},
  //     { englishWord: "lend, lent, lent", spanishTranslation: "prestar", rating: 0, image: " https://i.giphy.com/media/MdjqowHpLJpVXUApMk/200w.gif",},
  //     { englishWord: "seek, sought, sought", spanishTranslation: "buscar - solicitar", rating: 0, image: " https://i.giphy.com/media/mJ7C6QzV9UwVf0bkzr/200w.gif",},
  //     { englishWord: "light, lit, lit", spanishTranslation: "encender - prender", rating: 0, image: " https://i.giphy.com/media/l2JebisijdzVL2Cqs/200w.gif",},
  //     { englishWord: "speed, sped, sped", spanishTranslation: "acelerar - apresurarse - darse prisa", rating: 0, image: " https://i.giphy.com/media/qxM03tz9rg4RYThmkG/200w.gif",},
  //     { englishWord: "swear, swore, sworn", spanishTranslation: "jurar", rating: 0, image: " https://i.giphy.com/media/5t2ev2eCEzYWjag91c/200w.gif",},
  //     { englishWord: "tell, told, told", spanishTranslation: "decir - contar", rating: 0, image: " https://i.giphy.com/media/3ohhwrd3CjE7A8otzi/200w.gif",},
  //     { englishWord: "quit, quit, quit", spanishTranslation: "dejar-abandonar", rating: 0, image: " https://i.giphy.com/media/HIyGDBxdiQ5uJYTGbP/200w.gif",},
  //     { englishWord: "breed, bred, bred", spanishTranslation: "criar - educar", rating: 0, image: " https://i.giphy.com/media/noHdhIkGHcIhy/200w.gif",},
  //     { englishWord: "feed, fed, fed", spanishTranslation: "alimentar(se)", rating: 0, image: " https://i.giphy.com/media/W5Zf6k7mbnMRWnicfg/200w.gif",},
  //     { englishWord: "burn, burnt/burned, burnt/burned", spanishTranslation: "quemar - incendiar", rating: 0, image: " https://i.giphy.com/media/r9E1WzdMLUQNscbVTm/200w.gif",},
  //     { englishWord: "deal, dealt, dealt", spanishTranslation: "negociar - comerciar", rating: 0, image: " https://i.giphy.com/media/ojwMVxGqy4oRO4c8rw/200w.gif",},
  //     { englishWord: "creep, crept, crept", spanishTranslation: "arrastrarse - deslizarse - gatear", rating: 0, image: " https://i.giphy.com/media/26Ffci1HvhUK5gVLG/200w.gif",},
  //     { englishWord: "let, let, let", spanishTranslation: "dejar - permitir", rating: 0, image: " https://i.giphy.com/media/m6Zf7BamTPRcI/200w.gif",},
  //     { englishWord: "bleed, bled, bled", spanishTranslation: "sangrar", rating: 0, image: " https://i.giphy.com/media/QJtiS9rHFqauLNJ5cP/200w.gif",},
  //     { englishWord: "hang, hung, hung", spanishTranslation: "colgar - suspender", rating: 0, image: " https://i.giphy.com/media/cNeuWYGCJfRdS9j89F/200w.gif",},
  //     { englishWord: "cut, cut, cut", spanishTranslation: "cortar - recortar", rating: 0, image: " https://i.giphy.com/media/eKasUvPB01V4TFH2YA/200w.gif",},
  //     { englishWord: "flee, fled, fled", spanishTranslation: "evitar - huir de", rating: 0, image: " https://i.giphy.com/media/S3PjeN6iPYyxJYvdji/200w.gif",},
  //     { englishWord: "behold, beheld, beheld", spanishTranslation: "contemplar - mirar", rating: 0, image: " https://i.giphy.com/media/3oKIPvcLVLEnbTAqEU/200w.gif",},
  //     { englishWord: "teach, taught, taught", spanishTranslation: "enseñar", rating: 0, image: " https://i.giphy.com/media/l0MYLE9bob7mhosfu/200w.gif",},
  //     { englishWord: "lead, led, led", spanishTranslation: "conducir - liderar", rating: 0, image: " https://i.giphy.com/media/3orif4BtRvTgRedJF6/200w.gif",},
  //     { englishWord: "shoot, shot, shot", spanishTranslation: "tirar - disparar", rating: 0, image: " https://i.giphy.com/media/VEzspneHDuo4PQzKc3/200w.gif",},
  //     { englishWord: "sleep, slept, slept", spanishTranslation: "dormir", rating: 0, image: " https://i.giphy.com/media/kIRicSBQwa23pYExQT/200w.gif",},
  //     { englishWord: "feel, felt, felt", spanishTranslation: "sentir", rating: 0, image: " https://i.giphy.com/media/JRJzW4LosT4CoRa0TZ/200w.gif",},
  //     { englishWord: "fling, flung, flung", spanishTranslation: "arrojar - lanzar - tirar", rating: 0, image: " https://i.giphy.com/media/T2b7Jnt7rB9Li/200w.gif",},
  //     { englishWord: "swim, swam, swum", spanishTranslation: "nadar", rating: 0, image: " https://i.giphy.com/media/l3V0mnnGcVblF8bAI/200w.gif",},
  //     { englishWord: "string, strungs, strung", spanishTranslation: "atar(cordones)", rating: 0, image: " https://i.giphy.com/media/j6MMHvVSIAzhAiP2IZ/200w.gif",},
  //     { englishWord: "slide, slid, slid", spanishTranslation: "resbalar(se)", rating: 0, image: " https://i.giphy.com/media/3otPoOT462O0kTx5RK/200w.gif",},
  //     { englishWord: "find, found, found", spanishTranslation: "encontrar - hallar", rating: 0, image: " https://i.giphy.com/media/zmlCPKMlXwq6k/200w.gif",},
  //     { englishWord: "forbid, forbade, forbidden", spanishTranslation: "prohibir - privar", rating: 0, image: " https://i.giphy.com/media/Ch3UBdp7uI8to76zVl/200w.gif",},
  //     { englishWord: "ride, rode, ridden", spanishTranslation: "cabalgar - montar", rating: 0, image: " https://i.giphy.com/media/naXyAp2VYMR4k/200w.gif",},
  //     { englishWord: "freeze, froze, frozen", spanishTranslation: "congelar - helar", rating: 0, image: " https://i.giphy.com/media/d3mlmtNPoxNrt4Bi/200w.gif",},
  //     { englishWord: "beat, beat, beaten", spanishTranslation: "vencer - batir", rating: 0, image: " https://i.giphy.com/media/l3vRg3PXSVON7Rogo/200w.gif",},
  //     { englishWord: "run, ran, run", spanishTranslation: "correr", rating: 0, image: " https://i.giphy.com/media/3o7ZetIsjtbkgNE1I4/200w.gif",},
  //     { englishWord: "cling, clung, clung", spanishTranslation: "agarrar - aferrarse - adherirse", rating: 0, image: " https://i.giphy.com/media/2zoLgckxd9FxDgx6gD/200w.gif",},
  //     { englishWord: "swing, swung, swung", spanishTranslation: "balancearse - girar - columpiarse", rating: 0, image: " https://i.giphy.com/media/Kuw5gir5rTnaw/200w.gif",},
  //     { englishWord: "bring, brought, brought", spanishTranslation: "traer - llevar", rating: 0, image: " https://i.giphy.com/media/0XQYtbNg4JXibQWY9e/200w.gif",},
  //     { englishWord: "tear, tore, torn", spanishTranslation: "rasgar - desgarrar - arrancar", rating: 0, image: " https://i.giphy.com/media/3JOy7A3NxiCZUqJo9c/200w.gif",},
  //     { englishWord: "make, made, made", spanishTranslation: "hacer - fabricar", rating: 0, image: " https://i.giphy.com/media/34RQ5J9TJT6mc8WBi2/200w.gif",},
  //     { englishWord: "choose, chose, chosen", spanishTranslation: "escoger - elegir - optar", rating: 0, image: " https://i.giphy.com/media/3oipPTHYlTpCw8oBBy/200w.gif",},
  //     { englishWord: "upset, upset, upset", spanishTranslation: "alterar - perturbar", rating: 0, image: " https://i.giphy.com/media/GnqgAJvlpkK76/200w.gif",},
  //     { englishWord: "read, read, read", spanishTranslation: "leer", rating: 0, image: "https://i.giphy.com/media/8dYmJ6Buo3lYY/200w.gif",},
  //     { englishWord: "stand, stood, stood", spanishTranslation: "ponerse de pie - pararse", rating: 0, image: "https://i.giphy.com/media/j6volCQRaACpo5h4EM/200w.gif",},
  //     { englishWord: "spin, spun, spun", spanishTranslation: "hacer girar (vueltas)", rating: 0, image: "https://i.giphy.com/media/bXvwCQglnTGKs/200w.gif",},
  //     { englishWord: "leave, left, left", spanishTranslation: "salir - abandonar", rating: 0, image: "https://i.giphy.com/media/48FhEMYGWji8/200w.gif",},
  //     { englishWord: "strive, strove, striven", spanishTranslation: "esforzarse", rating: 0, image: "https://i.giphy.com/media/XiPg4fGi4RMPTJnFUF/200w.gif",},
  //     { englishWord: "dig, dug, dug", spanishTranslation: "cavar - excavar", rating: 0, image: "https://i.giphy.com/media/12bpEjD05ac2IM/200w.gif",},
  //     { englishWord: "blow, blew, blown", spanishTranslation: "soplar - ventear", rating: 0, image: "https://i.giphy.com/media/yoJC2P9fUkIm7lDMeA/200w.gif",},
  //     { englishWord: "eat, ate, eaten", spanishTranslation: "comer", rating: 0, image: "https://i.giphy.com/media/3osxY7eI6enqNBo2mQ/200w.gif",},
  //     { englishWord: "win, won, won", spanishTranslation: "ganar", rating: 0, image: "https://i.giphy.com/media/3ohs4su16JU4XsVKfe/200w.gif",},
  //     { englishWord: "awake, awoke, awoke", spanishTranslation: "despertar(se)", rating: 0, image: "https://i.giphy.com/media/FtPS6kvzFEiApsLisX/200w.gif",},
  //     { englishWord: "abide, abode, abode", spanishTranslation: "morar - habitar - tolerar", rating: 0, image: "https://i.giphy.com/media/ni2wk9VTYMw9O/200w.gif",},
  //     { englishWord: "strike, struck, struck", spanishTranslation: "golpear - pegar", rating: 0, image: "https://i.giphy.com/media/1YaJqvpJKkASs4f6ic/200w.gif",},
  //     { englishWord: "weave, wove, woven", spanishTranslation: "tejer", rating: 0, image: "https://i.giphy.com/media/bltiqBEjFQlaTnxd6C/200w.gif",},
  //     { englishWord: "forecast, forecast, forecast", spanishTranslation: "pronosticar", rating: 0, image: "https://i.giphy.com/media/tja7MJ6DYOenIR4oDc/200w.gif",},
  //     { englishWord: "spread, spread, spread", spanishTranslation: "extender - untar", rating: 0, image: "https://i.giphy.com/media/Jfu3UlHpJK1Hi/200w.gif",},
  //     { englishWord: "stink, stank, stunk", spanishTranslation: "apestar - oler mal", rating: 0, image: "https://i.giphy.com/media/TIWrHYuuOKc3j90Ylm/200w.gif",},
  //     { englishWord: "say, said, said", spanishTranslation: "decir", rating: 0, image: "https://i.giphy.com/media/U4NM7UyhnF5Pa/200w.gif",},
  //     { englishWord: "forgive, forgave, forgiven", spanishTranslation: "perdonar", rating: 0, image: "https://i.giphy.com/media/lpIqwGHhwmsNyAyrvy/200w.gif",},
  //     { englishWord: "spring, sprang, sprung", spanishTranslation: "saltar - brotar", rating: 0, image: "https://i.giphy.com/media/R9dVdx76BJFks/200w.gif",},
  //     { englishWord: "see, saw, seen", spanishTranslation: "ver", rating: 0, image: "https://i.giphy.com/media/cP6G0uiTHCzMUdrdS1/200w.gif",},
  //     { englishWord: "hit, hit, hit", spanishTranslation: "golpear - pegar", rating: 0, image: "https://i.giphy.com/media/qIfG2193qAwGgw4hdg/200w.gif",},
  //     { englishWord: "sign, signed, signed", spanishTranslation: "firmar", rating: 0, image: "https://i.giphy.com/media/l2JegHKlrPqqOjjig/200w.gif",},
  //     { englishWord: "spit, spit, spit", spanishTranslation: "escupir", rating: 0, image: "https://i.giphy.com/media/l0HU5bbgdW6qzJsmQ/200w.gif",},
  //     { englishWord: "overcome, overcame, overcome", spanishTranslation: "superar - triunfar", rating: 0, image: "https://i.giphy.com/media/1Xd9JPDm9CAaRe66oP/200w.gif",},
  //     { englishWord: "buy, bought, bought", spanishTranslation: "comprar - adquirir", rating: 0, image: "https://i.giphy.com/media/sDcfxFDozb3bO/200w.gif",},
  //     { englishWord: "lose, lost, lost", spanishTranslation: "perder", rating: 0, image: "https://i.giphy.com/media/UNNffDUqDJYs/200w.gif",},
  //     { englishWord: "hurt, hurt, hurt", spanishTranslation: "herir - lastimar", rating: 0, image: "https://i.giphy.com/media/13w5HmyiuaZ224/200w.gif",},
  //     { englishWord: "forget, forgot, forgotten", spanishTranslation: "olvidar", rating: 0, image: "https://i.giphy.com/media/3ohhwoBqhih33ck000/200w.gif",},
  //     { englishWord: "mistake, mistook, mistaken", spanishTranslation: "equivocarse", rating: 0, image: "https://i.giphy.com/media/3ohhwvAprUeTXBQxXy/200w.gif",},
  //     { englishWord: "wake, woke, woken", spanishTranslation: "despertar(se)", rating: 0, image: "https://i.giphy.com/media/WZj3l2HIRubde/200w.gif",},
  //     { englishWord: "bear, bore, born", spanishTranslation: "soportar - aguantar", rating: 0, image: "https://i.giphy.com/media/Ie4CIIvQS0bk3zwZlM/200w.gif",},
  //     { englishWord: "fall, fell, fallen", spanishTranslation: "caer(se)", rating: 0, image: "https://i.giphy.com/media/3oxRmGNqKwCzJ0AwPC/200w.gif",},
  //     { englishWord: "cast, cast, cast", spanishTranslation: "moldear - repartir - echar - tirar", rating: 0, image: "https://i.giphy.com/media/iFDKydfCn7PTZePMto/200w.gif",},
  //     { englishWord: "drive, drove, driven", spanishTranslation: "manejar - conducir", rating: 0, image: "https://i.giphy.com/media/4V2QpkTTYtr7us3iKM/200w.gif",},
  //     { englishWord: "lay, laid, laid", spanishTranslation: "poner - colocar - echar", rating: 0, image: "https://i.giphy.com/media/3o7WIN1WaLva5ORmfK/200w.gif",},
  //     { englishWord: "shrink, shrank, shrunk", spanishTranslation: "encoger - contraer", rating: 0, image: "https://i.giphy.com/media/5Yv6KywEdxUU4EjC1c/200w.gif",},
  //     { englishWord: "hear, heard, heard", spanishTranslation: "oir", rating: 0, image: "https://i.giphy.com/media/rhgwg4qBu97ISgbfni/200w.gif",},
  //     { englishWord: "show, showed, shown", spanishTranslation: "mostrar - enseñar", rating: 0, image: "https://i.giphy.com/media/10lib5POdEnKFO/200w.gif",},
  //     { englishWord: "wring, wrung, wrung", spanishTranslation: "escurrir - retorcer", rating: 0, image: "https://i.giphy.com/media/xdOspsxc8rWYE/200w.gif",},
  //     { englishWord: "take, took, taken", spanishTranslation: "tomar - agarrar - coger", rating: 0, image: "https://i.giphy.com/media/7JKTwn0tBu3ecZZQzx/200w.gif",},
  //     { englishWord: "fly, flew, flown", spanishTranslation: "volar - huir", rating: 0, image: "https://i.giphy.com/media/gZEBpuOkPuydi/200w.gif",},
  //     { englishWord: "give, gave, given", spanishTranslation: "dar - regalar", rating: 0, image: "https://i.giphy.com/media/PPEDuq1xCAf8sj75yw/200w.gif",},
  //     { englishWord: "wind, wound, wound", spanishTranslation: "enrollar", rating: 0, image: "https://i.giphy.com/media/5p0M9XGpSff1cniSEj/200w.gif",},
  //     { englishWord: "keep, kept, kept", spanishTranslation: "mantener - guardar", rating: 0, image: "https://i.giphy.com/media/LUBNhsWA67Saqv2uQe/200w.gif",},
  //     { englishWord: "spend, spend, spent", spanishTranslation: "gastar - pasar el tiempo", rating: 0, image: "https://i.giphy.com/media/d3mmdNnW5hkoUxTG/200w.gif",},
  //     { englishWord: "fight, fought, fought", spanishTranslation: "pelear - luchar", rating: 0, image: "https://i.giphy.com/media/3ohc0QQkTH6YK8g4zS/200w.gif",},
  //     { englishWord: "thrust, thrust, thrust", spanishTranslation: "clavar - empujar", rating: 0, image: "https://i.giphy.com/media/8Z5xJbiqa2hS25nweC/200w.gif",},
  //     { englishWord: "rid, rid, rid", spanishTranslation: "librarse de - deshacerse", rating: 0, image: "https://i.giphy.com/media/3ohzdGCQtxtZkqpBdK/200w.gif",},
  //   ],
  // },
];
